export const queryKeys = {
  health: {
    check: "healthCheck",
  },
  auth: {
    login: "authLogin",
    register: "authRegister",
    logout: "authLogout",
    me: "authMe",
  },
  capabilities: {
    list: "capabilitiesList",
    get: "capabilitiesGet",
    create: "capabilitiesCreate",
    update: "capabilitiesUpdate",
    delete: "capabilitiesDelete",
    bindings: "capabilitiesBindings",
    test: "capabilitiesTest",
  },
  bindings: {
    delete: "bindingsDelete",
  },
  workflows: {
    list: "workflowsList",
    get: "workflowsGet",
    create: "workflowsCreate",
    update: "workflowsUpdate",
    publish: "workflowsPublish",
    versions: "workflowsVersions",
    version: "workflowsVersion",
    compare: "workflowsCompare",
    simulate: "workflowsSimulate",
  },
  intents: {
    list: "intentsList",
  },
  projects: {
    list: "projectsList",
  },
  mcpConnections: {
    list: "mcpConnectionsList",
    get: "mcpConnectionsGet",
    create: "mcpConnectionsCreate",
    update: "mcpConnectionsUpdate",
    delete: "mcpConnectionsDelete",
    enable: "mcpConnectionsEnable",
    disable: "mcpConnectionsDisable",
    test: "mcpConnectionsTest",
    diagnose: "mcpConnectionsDiagnose",
    resetHealth: "mcpConnectionsResetHealth",
    rotateCredential: "mcpConnectionsRotateCredential",
    revokeCredential: "mcpConnectionsRevokeCredential",
    credentialStatus: "mcpConnectionsCredentialStatus",
    oauthStart: "mcpConnectionsOAuthStart",
    oauthDisconnect: "mcpConnectionsOAuthDisconnect",
    oauthStatus: "mcpConnectionsOAuthStatus",
    tools: "mcpConnectionsTools",
    refreshTools: "mcpConnectionsRefreshTools",
    updateTool: "mcpConnectionsUpdateTool",
  },
  projectMCPBindings: {
    options: "projectMCPBindingOptions",
    list: "projectMCPBindingsList",
    upsert: "projectMCPBindingUpsert",
    delete: "projectMCPBindingDelete",
  },
  audit: {
    list: "auditList",
  },
  runtimeInstances: {
    list: "runtimeInstancesList",
    get: "runtimeInstanceGet",
    debugTrace: "runtimeInstanceDebugTrace",
  },
  admin: {
    apiKeys: "adminAPIKeys",
    createAPIKey: "adminCreateAPIKey",
    revokeAPIKey: "adminRevokeAPIKey",
    tenant: "adminTenant",
    members: "adminMembers",
    updateTenant: "adminUpdateTenant",
    updateMemberRole: "adminUpdateMemberRole",
    removeMember: "adminRemoveMember",
    instances: "adminInstances",
    suspendInstance: "adminSuspendInstance",
    resumeInstance: "adminResumeInstance",
    retryInstance: "adminRetryInstance",
    events: "adminEvents",
    event: "adminEvent",
  },
}
