export const queryKeys = {
  health: {
    check: "healthCheck",
  },
  auth: {
    login: "authLogin",
    register: "authRegister",
    logout: "authLogout",
    me: "authMe",
  },
  capabilities: {
    list: "capabilitiesList",
    get: "capabilitiesGet",
    create: "capabilitiesCreate",
    update: "capabilitiesUpdate",
    delete: "capabilitiesDelete",
    bindings: "capabilitiesBindings",
    test: "capabilitiesTest",
  },
  bindings: {
    delete: "bindingsDelete",
  },
  workflows: {
    list: "workflowsList",
    get: "workflowsGet",
    create: "workflowsCreate",
    update: "workflowsUpdate",
    publish: "workflowsPublish",
    versions: "workflowsVersions",
    version: "workflowsVersion",
    compare: "workflowsCompare",
    simulate: "workflowsSimulate",
  },
  audit: {
    list: "auditList",
  },
  runtimeInstances: {
    list: "runtimeInstancesList",
    get: "runtimeInstanceGet",
    debugTrace: "runtimeInstanceDebugTrace",
  },
  admin: {
    tenant: "adminTenant",
    members: "adminMembers",
    updateTenant: "adminUpdateTenant",
    updateMemberRole: "adminUpdateMemberRole",
    removeMember: "adminRemoveMember",
    instances: "adminInstances",
    suspendInstance: "adminSuspendInstance",
    resumeInstance: "adminResumeInstance",
    retryInstance: "adminRetryInstance",
    events: "adminEvents",
    event: "adminEvent",
  },
}
