// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAdminMemberships = `-- name: CountAdminMemberships :one
SELECT COUNT(*)
FROM role_assignments AS ra
JOIN users AS u ON u.id = ra.user_id
WHERE ra.tenant_id = $1
  AND (
    $2::text IS NULL
    OR u.name ILIKE '%' || $2 || '%'
    OR u.email ILIKE '%' || $2 || '%'
  )
`

type CountAdminMembershipsParams struct {
	TenantID uuid.UUID      `json:"tenant_id"`
	Search   sql.NullString `json:"search"`
}

func (q *Queries) CountAdminMemberships(ctx context.Context, arg CountAdminMembershipsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminMemberships, arg.TenantID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminOwners = `-- name: CountAdminOwners :one
SELECT COUNT(*)
FROM role_assignments
WHERE tenant_id = $1 AND role = 'OWNER'
`

func (q *Queries) CountAdminOwners(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminOwners, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findAdminMembership = `-- name: FindAdminMembership :one
SELECT
  ra.id AS role_assignment_id,
  ra.user_id,
  ra.tenant_id,
  ra.role,
  ra.created_at AS role_created_at,
  ra.updated_at AS role_updated_at,
  u.email,
  u.name,
  u.status,
  u.photo
FROM role_assignments AS ra
JOIN users AS u ON u.id = ra.user_id
WHERE ra.tenant_id = $1 AND ra.user_id = $2
LIMIT 1
`

type FindAdminMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type FindAdminMembershipRow struct {
	RoleAssignmentID uuid.UUID      `json:"role_assignment_id"`
	UserID           uuid.UUID      `json:"user_id"`
	TenantID         uuid.UUID      `json:"tenant_id"`
	Role             string         `json:"role"`
	RoleCreatedAt    time.Time      `json:"role_created_at"`
	RoleUpdatedAt    time.Time      `json:"role_updated_at"`
	Email            string         `json:"email"`
	Name             string         `json:"name"`
	Status           UserStatus     `json:"status"`
	Photo            sql.NullString `json:"photo"`
}

func (q *Queries) FindAdminMembership(ctx context.Context, arg FindAdminMembershipParams) (FindAdminMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, findAdminMembership, arg.TenantID, arg.UserID)
	var i FindAdminMembershipRow
	err := row.Scan(
		&i.RoleAssignmentID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.RoleCreatedAt,
		&i.RoleUpdatedAt,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Photo,
	)
	return i, err
}

const findTenantByID = `-- name: FindTenantByID :one

SELECT id, name, slug, description, created_at, updated_at
FROM tenants
WHERE id = $1
LIMIT 1
`

// Tenant profile and membership queries for the Admin Console. All lookups are
// explicitly tenant-scoped; the caller never supplies a tenant through a body.
func (q *Queries) FindTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, findTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminMemberships = `-- name: ListAdminMemberships :many
SELECT
  ra.id AS role_assignment_id,
  ra.user_id,
  ra.tenant_id,
  ra.role,
  ra.created_at AS role_created_at,
  ra.updated_at AS role_updated_at,
  u.email,
  u.name,
  u.status,
  u.photo
FROM role_assignments AS ra
JOIN users AS u ON u.id = ra.user_id
WHERE ra.tenant_id = $1
  AND (
    $2::text IS NULL
    OR u.name ILIKE '%' || $2 || '%'
    OR u.email ILIKE '%' || $2 || '%'
  )
ORDER BY u.name ASC, ra.created_at DESC
LIMIT $4 OFFSET $3
`

type ListAdminMembershipsParams struct {
	TenantID   uuid.UUID      `json:"tenant_id"`
	Search     sql.NullString `json:"search"`
	PageOffset int32          `json:"page_offset"`
	PageSize   int32          `json:"page_size"`
}

type ListAdminMembershipsRow struct {
	RoleAssignmentID uuid.UUID      `json:"role_assignment_id"`
	UserID           uuid.UUID      `json:"user_id"`
	TenantID         uuid.UUID      `json:"tenant_id"`
	Role             string         `json:"role"`
	RoleCreatedAt    time.Time      `json:"role_created_at"`
	RoleUpdatedAt    time.Time      `json:"role_updated_at"`
	Email            string         `json:"email"`
	Name             string         `json:"name"`
	Status           UserStatus     `json:"status"`
	Photo            sql.NullString `json:"photo"`
}

func (q *Queries) ListAdminMemberships(ctx context.Context, arg ListAdminMembershipsParams) ([]ListAdminMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminMemberships,
		arg.TenantID,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminMembershipsRow
	for rows.Next() {
		var i ListAdminMembershipsRow
		if err := rows.Scan(
			&i.RoleAssignmentID,
			&i.UserID,
			&i.TenantID,
			&i.Role,
			&i.RoleCreatedAt,
			&i.RoleUpdatedAt,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.Photo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAdminMembership = `-- name: RemoveAdminMembership :exec
DELETE FROM role_assignments
WHERE tenant_id = $1 AND user_id = $2
`

type RemoveAdminMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveAdminMembership(ctx context.Context, arg RemoveAdminMembershipParams) error {
	_, err := q.db.ExecContext(ctx, removeAdminMembership, arg.TenantID, arg.UserID)
	return err
}

const updateTenantProfile = `-- name: UpdateTenantProfile :one
UPDATE tenants
SET name = $2, slug = $3, description = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, created_at, updated_at
`

type UpdateTenantProfileParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateTenantProfile(ctx context.Context, arg UpdateTenantProfileParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenantProfile,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdminMembershipRole = `-- name: UpsertAdminMembershipRole :one
INSERT INTO role_assignments (user_id, tenant_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, tenant_id)
DO UPDATE SET role = EXCLUDED.role, updated_at = NOW()
RETURNING id, user_id, tenant_id, role, created_at, updated_at
`

type UpsertAdminMembershipRoleParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Role     string    `json:"role"`
}

func (q *Queries) UpsertAdminMembershipRole(ctx context.Context, arg UpsertAdminMembershipRoleParams) (RoleAssignment, error) {
	row := q.db.QueryRowContext(ctx, upsertAdminMembershipRole, arg.UserID, arg.TenantID, arg.Role)
	var i RoleAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
