// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_key.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addAPIKeyProject = `-- name: AddAPIKeyProject :exec
INSERT INTO auth_api_key_projects (api_key_id, project_id)
VALUES ($1, $2)
`

type AddAPIKeyProjectParams struct {
	ApiKeyID  uuid.UUID `json:"api_key_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) AddAPIKeyProject(ctx context.Context, arg AddAPIKeyProjectParams) error {
	_, err := q.db.ExecContext(ctx, addAPIKeyProject, arg.ApiKeyID, arg.ProjectID)
	return err
}

const addAPIKeyScope = `-- name: AddAPIKeyScope :exec
INSERT INTO auth_api_key_scopes (api_key_id, scope)
VALUES ($1, $2)
`

type AddAPIKeyScopeParams struct {
	ApiKeyID uuid.UUID `json:"api_key_id"`
	Scope    string    `json:"scope"`
}

func (q *Queries) AddAPIKeyScope(ctx context.Context, arg AddAPIKeyScopeParams) error {
	_, err := q.db.ExecContext(ctx, addAPIKeyScope, arg.ApiKeyID, arg.Scope)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO auth_api_keys (tenant_id, name, key_prefix, key_verifier, default_project_id, expires_at, created_by)
VALUES ($1, $2, $3, $4, $6, $7, $5)
RETURNING id, tenant_id, name, key_prefix, key_verifier, default_project_id, expires_at, revoked_at, last_used_at, created_by, created_at, updated_at
`

type CreateAPIKeyParams struct {
	TenantID         uuid.UUID     `json:"tenant_id"`
	Name             string        `json:"name"`
	KeyPrefix        string        `json:"key_prefix"`
	KeyVerifier      []byte        `json:"key_verifier"`
	CreatedBy        string        `json:"created_by"`
	DefaultProjectID uuid.NullUUID `json:"default_project_id"`
	ExpiresAt        sql.NullTime  `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (AuthApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.TenantID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyVerifier,
		arg.CreatedBy,
		arg.DefaultProjectID,
		arg.ExpiresAt,
	)
	var i AuthApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyVerifier,
		&i.DefaultProjectID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAPIKeyByPrefix = `-- name: FindAPIKeyByPrefix :one
SELECT id, tenant_id, name, key_prefix, key_verifier, default_project_id, expires_at, revoked_at, last_used_at, created_by, created_at, updated_at
FROM auth_api_keys
WHERE key_prefix = $1
LIMIT 1
`

func (q *Queries) FindAPIKeyByPrefix(ctx context.Context, keyPrefix string) (AuthApiKey, error) {
	row := q.db.QueryRowContext(ctx, findAPIKeyByPrefix, keyPrefix)
	var i AuthApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyVerifier,
		&i.DefaultProjectID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeyProjects = `-- name: ListAPIKeyProjects :many
SELECT project_id
FROM auth_api_key_projects
WHERE api_key_id = $1
ORDER BY project_id ASC
`

func (q *Queries) ListAPIKeyProjects(ctx context.Context, apiKeyID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeyProjects, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var project_id uuid.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeyScopes = `-- name: ListAPIKeyScopes :many
SELECT scope
FROM auth_api_key_scopes
WHERE api_key_id = $1
ORDER BY scope ASC
`

func (q *Queries) ListAPIKeyScopes(ctx context.Context, apiKeyID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeyScopes, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByTenant = `-- name: ListAPIKeysByTenant :many
SELECT id, tenant_id, name, key_prefix, key_verifier, default_project_id, expires_at, revoked_at, last_used_at, created_by, created_at, updated_at
FROM auth_api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]AuthApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthApiKey
	for rows.Next() {
		var i AuthApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyVerifier,
			&i.DefaultProjectID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE auth_api_keys
SET revoked_at = NOW(), updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
RETURNING id, tenant_id, name, key_prefix, key_verifier, default_project_id, expires_at, revoked_at, last_used_at, created_by, created_at, updated_at
`

type RevokeAPIKeyParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (AuthApiKey, error) {
	row := q.db.QueryRowContext(ctx, revokeAPIKey, arg.ID, arg.TenantID)
	var i AuthApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyVerifier,
		&i.DefaultProjectID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE auth_api_keys
SET last_used_at = NOW(), updated_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, touchAPIKeyLastUsed, id)
	return err
}
