// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capability_evidence.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const findCapabilityEvidenceByIdempotency = `-- name: FindCapabilityEvidenceByIdempotency :one
SELECT id, tenant_id, project_id, workflow_instance_id, state_id, capability_id,
  capability_name, provider_server, provider_tool, correlation_id, idempotency_key,
  status, result, error, created_at, updated_at
FROM capability_execution_evidence
WHERE tenant_id = $1 AND project_id = $2 AND workflow_instance_id = $3
  AND state_id = $4 AND capability_id = $5 AND idempotency_key = $6
LIMIT 1
`

type FindCapabilityEvidenceByIdempotencyParams struct {
	TenantID           uuid.UUID `json:"tenant_id"`
	ProjectID          uuid.UUID `json:"project_id"`
	WorkflowInstanceID uuid.UUID `json:"workflow_instance_id"`
	StateID            string    `json:"state_id"`
	CapabilityID       uuid.UUID `json:"capability_id"`
	IdempotencyKey     string    `json:"idempotency_key"`
}

func (q *Queries) FindCapabilityEvidenceByIdempotency(ctx context.Context, arg FindCapabilityEvidenceByIdempotencyParams) (CapabilityExecutionEvidence, error) {
	row := q.db.QueryRowContext(ctx, findCapabilityEvidenceByIdempotency,
		arg.TenantID,
		arg.ProjectID,
		arg.WorkflowInstanceID,
		arg.StateID,
		arg.CapabilityID,
		arg.IdempotencyKey,
	)
	var i CapabilityExecutionEvidence
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.WorkflowInstanceID,
		&i.StateID,
		&i.CapabilityID,
		&i.CapabilityName,
		&i.ProviderServer,
		&i.ProviderTool,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCapabilityEvidenceByInstanceState = `-- name: ListCapabilityEvidenceByInstanceState :many
SELECT id, tenant_id, project_id, workflow_instance_id, state_id, capability_id,
  capability_name, provider_server, provider_tool, correlation_id, idempotency_key,
  status, result, error, created_at, updated_at
FROM capability_execution_evidence
WHERE tenant_id = $1 AND workflow_instance_id = $2 AND state_id = $3
ORDER BY created_at ASC
`

type ListCapabilityEvidenceByInstanceStateParams struct {
	TenantID           uuid.UUID `json:"tenant_id"`
	WorkflowInstanceID uuid.UUID `json:"workflow_instance_id"`
	StateID            string    `json:"state_id"`
}

func (q *Queries) ListCapabilityEvidenceByInstanceState(ctx context.Context, arg ListCapabilityEvidenceByInstanceStateParams) ([]CapabilityExecutionEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilityEvidenceByInstanceState, arg.TenantID, arg.WorkflowInstanceID, arg.StateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityExecutionEvidence
	for rows.Next() {
		var i CapabilityExecutionEvidence
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.WorkflowInstanceID,
			&i.StateID,
			&i.CapabilityID,
			&i.CapabilityName,
			&i.ProviderServer,
			&i.ProviderTool,
			&i.CorrelationID,
			&i.IdempotencyKey,
			&i.Status,
			&i.Result,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilityEvidenceByState = `-- name: ListCapabilityEvidenceByState :many
SELECT id, tenant_id, project_id, workflow_instance_id, state_id, capability_id,
  capability_name, provider_server, provider_tool, correlation_id, idempotency_key,
  status, result, error, created_at, updated_at
FROM capability_execution_evidence
WHERE tenant_id = $1 AND project_id = $2 AND workflow_instance_id = $3 AND state_id = $4
ORDER BY created_at ASC
`

type ListCapabilityEvidenceByStateParams struct {
	TenantID           uuid.UUID `json:"tenant_id"`
	ProjectID          uuid.UUID `json:"project_id"`
	WorkflowInstanceID uuid.UUID `json:"workflow_instance_id"`
	StateID            string    `json:"state_id"`
}

func (q *Queries) ListCapabilityEvidenceByState(ctx context.Context, arg ListCapabilityEvidenceByStateParams) ([]CapabilityExecutionEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilityEvidenceByState,
		arg.TenantID,
		arg.ProjectID,
		arg.WorkflowInstanceID,
		arg.StateID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityExecutionEvidence
	for rows.Next() {
		var i CapabilityExecutionEvidence
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.WorkflowInstanceID,
			&i.StateID,
			&i.CapabilityID,
			&i.CapabilityName,
			&i.ProviderServer,
			&i.ProviderTool,
			&i.CorrelationID,
			&i.IdempotencyKey,
			&i.Status,
			&i.Result,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCapabilityExecutionEvidence = `-- name: UpsertCapabilityExecutionEvidence :one
INSERT INTO capability_execution_evidence (
  tenant_id, project_id, workflow_instance_id, state_id, capability_id,
  capability_name, provider_server, provider_tool, correlation_id,
  idempotency_key, status, result, error
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (tenant_id, workflow_instance_id, state_id, capability_id, idempotency_key)
DO UPDATE SET
  provider_server = EXCLUDED.provider_server,
  provider_tool = EXCLUDED.provider_tool,
  correlation_id = EXCLUDED.correlation_id,
  status = EXCLUDED.status,
  result = EXCLUDED.result,
  error = EXCLUDED.error,
  updated_at = NOW()
RETURNING id, tenant_id, project_id, workflow_instance_id, state_id, capability_id,
  capability_name, provider_server, provider_tool, correlation_id, idempotency_key,
  status, result, error, created_at, updated_at
`

type UpsertCapabilityExecutionEvidenceParams struct {
	TenantID           uuid.UUID             `json:"tenant_id"`
	ProjectID          uuid.UUID             `json:"project_id"`
	WorkflowInstanceID uuid.UUID             `json:"workflow_instance_id"`
	StateID            string                `json:"state_id"`
	CapabilityID       uuid.UUID             `json:"capability_id"`
	CapabilityName     string                `json:"capability_name"`
	ProviderServer     string                `json:"provider_server"`
	ProviderTool       string                `json:"provider_tool"`
	CorrelationID      sql.NullString        `json:"correlation_id"`
	IdempotencyKey     string                `json:"idempotency_key"`
	Status             string                `json:"status"`
	Result             json.RawMessage       `json:"result"`
	Error              pqtype.NullRawMessage `json:"error"`
}

func (q *Queries) UpsertCapabilityExecutionEvidence(ctx context.Context, arg UpsertCapabilityExecutionEvidenceParams) (CapabilityExecutionEvidence, error) {
	row := q.db.QueryRowContext(ctx, upsertCapabilityExecutionEvidence,
		arg.TenantID,
		arg.ProjectID,
		arg.WorkflowInstanceID,
		arg.StateID,
		arg.CapabilityID,
		arg.CapabilityName,
		arg.ProviderServer,
		arg.ProviderTool,
		arg.CorrelationID,
		arg.IdempotencyKey,
		arg.Status,
		arg.Result,
		arg.Error,
	)
	var i CapabilityExecutionEvidence
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.WorkflowInstanceID,
		&i.StateID,
		&i.CapabilityID,
		&i.CapabilityName,
		&i.ProviderServer,
		&i.ProviderTool,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
