// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capability.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const bindCapability = `-- name: BindCapability :one
INSERT INTO capability_bindings (tenant_id, capability_id, scope_type, scope_id, permission)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, capability_id, scope_type, scope_id, permission, created_at, updated_at
`

type BindCapabilityParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	CapabilityID uuid.UUID `json:"capability_id"`
	ScopeType    string    `json:"scope_type"`
	ScopeID      string    `json:"scope_id"`
	Permission   string    `json:"permission"`
}

func (q *Queries) BindCapability(ctx context.Context, arg BindCapabilityParams) (CapabilityBinding, error) {
	row := q.db.QueryRowContext(ctx, bindCapability,
		arg.TenantID,
		arg.CapabilityID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Permission,
	)
	var i CapabilityBinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CapabilityID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Permission,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCapability = `-- name: CreateCapability :one
INSERT INTO capabilities (tenant_id, name, description, provider_type, provider_id, input_schema, output_schema, status, version, credential_reference)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, name, description, provider_type, provider_id, input_schema, output_schema, status, version, credential_reference, created_at, updated_at
`

type CreateCapabilityParams struct {
	TenantID            uuid.UUID       `json:"tenant_id"`
	Name                string          `json:"name"`
	Description         sql.NullString  `json:"description"`
	ProviderType        string          `json:"provider_type"`
	ProviderID          sql.NullString  `json:"provider_id"`
	InputSchema         json.RawMessage `json:"input_schema"`
	OutputSchema        json.RawMessage `json:"output_schema"`
	Status              string          `json:"status"`
	Version             int32           `json:"version"`
	CredentialReference sql.NullString  `json:"credential_reference"`
}

func (q *Queries) CreateCapability(ctx context.Context, arg CreateCapabilityParams) (Capability, error) {
	row := q.db.QueryRowContext(ctx, createCapability,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.ProviderType,
		arg.ProviderID,
		arg.InputSchema,
		arg.OutputSchema,
		arg.Status,
		arg.Version,
		arg.CredentialReference,
	)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ProviderType,
		&i.ProviderID,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Status,
		&i.Version,
		&i.CredentialReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCapabilityByID = `-- name: FindCapabilityByID :one
SELECT id, tenant_id, name, description, provider_type, provider_id, input_schema, output_schema, status, version, credential_reference, created_at, updated_at
FROM capabilities
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type FindCapabilityByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindCapabilityByID(ctx context.Context, arg FindCapabilityByIDParams) (Capability, error) {
	row := q.db.QueryRowContext(ctx, findCapabilityByID, arg.ID, arg.TenantID)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ProviderType,
		&i.ProviderID,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Status,
		&i.Version,
		&i.CredentialReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCapabilityByName = `-- name: FindCapabilityByName :one
SELECT id, tenant_id, name, description, provider_type, provider_id, input_schema, output_schema, status, version, credential_reference, created_at, updated_at
FROM capabilities
WHERE name = $1 AND tenant_id = $2
LIMIT 1
`

type FindCapabilityByNameParams struct {
	Name     string    `json:"name"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindCapabilityByName(ctx context.Context, arg FindCapabilityByNameParams) (Capability, error) {
	row := q.db.QueryRowContext(ctx, findCapabilityByName, arg.Name, arg.TenantID)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ProviderType,
		&i.ProviderID,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Status,
		&i.Version,
		&i.CredentialReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPolicyByType = `-- name: FindPolicyByType :one
SELECT id, tenant_id, scope_type, scope_id, type, content, created_at, updated_at
FROM policies
WHERE tenant_id = $1 AND scope_type = $2 AND scope_id = $3 AND type = $4
LIMIT 1
`

type FindPolicyByTypeParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ScopeType string    `json:"scope_type"`
	ScopeID   string    `json:"scope_id"`
	Type      string    `json:"type"`
}

func (q *Queries) FindPolicyByType(ctx context.Context, arg FindPolicyByTypeParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, findPolicyByType,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Type,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBindingsByCapability = `-- name: ListBindingsByCapability :many
SELECT id, tenant_id, capability_id, scope_type, scope_id, permission, created_at, updated_at
FROM capability_bindings
WHERE capability_id = $1 AND tenant_id = $2
ORDER BY scope_type ASC, scope_id ASC
`

type ListBindingsByCapabilityParams struct {
	CapabilityID uuid.UUID `json:"capability_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListBindingsByCapability(ctx context.Context, arg ListBindingsByCapabilityParams) ([]CapabilityBinding, error) {
	rows, err := q.db.QueryContext(ctx, listBindingsByCapability, arg.CapabilityID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityBinding
	for rows.Next() {
		var i CapabilityBinding
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CapabilityID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Permission,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBindingsByScope = `-- name: ListBindingsByScope :many
SELECT id, tenant_id, capability_id, scope_type, scope_id, permission, created_at, updated_at
FROM capability_bindings
WHERE scope_type = $1 AND scope_id = $2 AND tenant_id = $3
ORDER BY capability_id ASC
`

type ListBindingsByScopeParams struct {
	ScopeType string    `json:"scope_type"`
	ScopeID   string    `json:"scope_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListBindingsByScope(ctx context.Context, arg ListBindingsByScopeParams) ([]CapabilityBinding, error) {
	rows, err := q.db.QueryContext(ctx, listBindingsByScope, arg.ScopeType, arg.ScopeID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityBinding
	for rows.Next() {
		var i CapabilityBinding
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CapabilityID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Permission,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilitiesByTenant = `-- name: ListCapabilitiesByTenant :many
SELECT id, tenant_id, name, description, provider_type, provider_id, input_schema, output_schema, status, version, credential_reference, created_at, updated_at
FROM capabilities
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCapabilitiesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Capability, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilitiesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capability
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ProviderType,
			&i.ProviderID,
			&i.InputSchema,
			&i.OutputSchema,
			&i.Status,
			&i.Version,
			&i.CredentialReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesByScope = `-- name: ListPoliciesByScope :many
SELECT id, tenant_id, scope_type, scope_id, type, content, created_at, updated_at
FROM policies
WHERE tenant_id = $1 AND scope_type = $2 AND scope_id = $3
ORDER BY type ASC
`

type ListPoliciesByScopeParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ScopeType string    `json:"scope_type"`
	ScopeID   string    `json:"scope_id"`
}

func (q *Queries) ListPoliciesByScope(ctx context.Context, arg ListPoliciesByScopeParams) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, listPoliciesByScope, arg.TenantID, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCapabilityStatus = `-- name: UpdateCapabilityStatus :one
UPDATE capabilities
SET status = $3, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, description, provider_type, provider_id, input_schema, output_schema, status, version, credential_reference, created_at, updated_at
`

type UpdateCapabilityStatusParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateCapabilityStatus(ctx context.Context, arg UpdateCapabilityStatusParams) (Capability, error) {
	row := q.db.QueryRowContext(ctx, updateCapabilityStatus, arg.ID, arg.TenantID, arg.Status)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ProviderType,
		&i.ProviderID,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Status,
		&i.Version,
		&i.CredentialReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPolicy = `-- name: UpsertPolicy :one
INSERT INTO policies (tenant_id, scope_type, scope_id, type, content)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, scope_type, scope_id, type)
DO UPDATE SET content = EXCLUDED.content, updated_at = NOW()
RETURNING id, tenant_id, scope_type, scope_id, type, content, created_at, updated_at
`

type UpsertPolicyParams struct {
	TenantID  uuid.UUID       `json:"tenant_id"`
	ScopeType string          `json:"scope_type"`
	ScopeID   string          `json:"scope_id"`
	Type      string          `json:"type"`
	Content   json.RawMessage `json:"content"`
}

func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, upsertPolicy,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Type,
		arg.Content,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
