// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteContext = `-- name: DeleteContext :exec
DELETE FROM context_records
WHERE tenant_id = $1 AND scope_type = $2 AND scope_id = $3 AND key = $4
`

type DeleteContextParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ScopeType string    `json:"scope_type"`
	ScopeID   string    `json:"scope_id"`
	Key       string    `json:"key"`
}

func (q *Queries) DeleteContext(ctx context.Context, arg DeleteContextParams) error {
	_, err := q.db.ExecContext(ctx, deleteContext,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Key,
	)
	return err
}

const deleteMemoryReference = `-- name: DeleteMemoryReference :exec
DELETE FROM memory_references
WHERE tenant_id = $1 AND owner_type = $2 AND owner_id = $3 AND name = $4
`

type DeleteMemoryReferenceParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	OwnerType string    `json:"owner_type"`
	OwnerID   string    `json:"owner_id"`
	Name      string    `json:"name"`
}

func (q *Queries) DeleteMemoryReference(ctx context.Context, arg DeleteMemoryReferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteMemoryReference,
		arg.TenantID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Name,
	)
	return err
}

const findContextByScope = `-- name: FindContextByScope :one
SELECT id, tenant_id, scope_type, scope_id, key, value, version, created_at, updated_at
FROM context_records
WHERE tenant_id = $1 AND scope_type = $2 AND scope_id = $3 AND key = $4
LIMIT 1
`

type FindContextByScopeParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ScopeType string    `json:"scope_type"`
	ScopeID   string    `json:"scope_id"`
	Key       string    `json:"key"`
}

func (q *Queries) FindContextByScope(ctx context.Context, arg FindContextByScopeParams) (ContextRecord, error) {
	row := q.db.QueryRowContext(ctx, findContextByScope,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Key,
	)
	var i ContextRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Key,
		&i.Value,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMemoryReference = `-- name: FindMemoryReference :one
SELECT id, tenant_id, owner_type, owner_id, name, value, source_workflow_instance_id, created_at, updated_at
FROM memory_references
WHERE tenant_id = $1 AND owner_type = $2 AND owner_id = $3 AND name = $4
LIMIT 1
`

type FindMemoryReferenceParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	OwnerType string    `json:"owner_type"`
	OwnerID   string    `json:"owner_id"`
	Name      string    `json:"name"`
}

func (q *Queries) FindMemoryReference(ctx context.Context, arg FindMemoryReferenceParams) (MemoryReference, error) {
	row := q.db.QueryRowContext(ctx, findMemoryReference,
		arg.TenantID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Name,
	)
	var i MemoryReference
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Name,
		&i.Value,
		&i.SourceWorkflowInstanceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContextByScope = `-- name: ListContextByScope :many
SELECT id, tenant_id, scope_type, scope_id, key, value, version, created_at, updated_at
FROM context_records
WHERE tenant_id = $1 AND scope_type = $2 AND scope_id = $3
ORDER BY created_at ASC
`

type ListContextByScopeParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ScopeType string    `json:"scope_type"`
	ScopeID   string    `json:"scope_id"`
}

func (q *Queries) ListContextByScope(ctx context.Context, arg ListContextByScopeParams) ([]ContextRecord, error) {
	rows, err := q.db.QueryContext(ctx, listContextByScope, arg.TenantID, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextRecord
	for rows.Next() {
		var i ContextRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Key,
			&i.Value,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryByOwner = `-- name: ListMemoryByOwner :many
SELECT id, tenant_id, owner_type, owner_id, name, value, source_workflow_instance_id, created_at, updated_at
FROM memory_references
WHERE tenant_id = $1 AND owner_type = $2 AND owner_id = $3
ORDER BY created_at ASC
`

type ListMemoryByOwnerParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	OwnerType string    `json:"owner_type"`
	OwnerID   string    `json:"owner_id"`
}

func (q *Queries) ListMemoryByOwner(ctx context.Context, arg ListMemoryByOwnerParams) ([]MemoryReference, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryByOwner, arg.TenantID, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryReference
	for rows.Next() {
		var i MemoryReference
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Name,
			&i.Value,
			&i.SourceWorkflowInstanceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContext = `-- name: UpsertContext :one

INSERT INTO context_records (tenant_id, scope_type, scope_id, key, value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, scope_type, scope_id, key)
DO UPDATE SET
  value      = EXCLUDED.value,
  version    = context_records.version + 1,
  updated_at = NOW()
WHERE context_records.version = $6
RETURNING id, tenant_id, scope_type, scope_id, key, value, version, created_at, updated_at
`

type UpsertContextParams struct {
	TenantID  uuid.UUID       `json:"tenant_id"`
	ScopeType string          `json:"scope_type"`
	ScopeID   string          `json:"scope_id"`
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	Version   int32           `json:"version"`
}

// Scoped runtime context (PRD §23, §36, §131) and persistent memory references
// (PRD §24, §43.2). All queries are tenant-scoped (PRD §4, §96).
func (q *Queries) UpsertContext(ctx context.Context, arg UpsertContextParams) (ContextRecord, error) {
	row := q.db.QueryRowContext(ctx, upsertContext,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Key,
		arg.Value,
		arg.Version,
	)
	var i ContextRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Key,
		&i.Value,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMemoryReference = `-- name: UpsertMemoryReference :one

INSERT INTO memory_references (tenant_id, owner_type, owner_id, name, value, source_workflow_instance_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, owner_type, owner_id, name)
DO UPDATE SET
  value                       = EXCLUDED.value,
  source_workflow_instance_id = EXCLUDED.source_workflow_instance_id,
  updated_at                  = NOW()
RETURNING id, tenant_id, owner_type, owner_id, name, value, source_workflow_instance_id, created_at, updated_at
`

type UpsertMemoryReferenceParams struct {
	TenantID                 uuid.UUID       `json:"tenant_id"`
	OwnerType                string          `json:"owner_type"`
	OwnerID                  string          `json:"owner_id"`
	Name                     string          `json:"name"`
	Value                    json.RawMessage `json:"value"`
	SourceWorkflowInstanceID uuid.NullUUID   `json:"source_workflow_instance_id"`
}

// Persistent memory references (PRD §24, §43.2).
func (q *Queries) UpsertMemoryReference(ctx context.Context, arg UpsertMemoryReferenceParams) (MemoryReference, error) {
	row := q.db.QueryRowContext(ctx, upsertMemoryReference,
		arg.TenantID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Name,
		arg.Value,
		arg.SourceWorkflowInstanceID,
	)
	var i MemoryReference
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Name,
		&i.Value,
		&i.SourceWorkflowInstanceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
