// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO events (tenant_id, event_id, type, source, aggregate_id, workflow_instance_id, timestamp, payload, correlation_id, causation_id, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, event_id, type, source, aggregate_id, workflow_instance_id, sequence, timestamp, payload, correlation_id, causation_id, idempotency_key, created_at
`

type AppendEventParams struct {
	TenantID           uuid.UUID       `json:"tenant_id"`
	EventID            string          `json:"event_id"`
	Type               string          `json:"type"`
	Source             string          `json:"source"`
	AggregateID        sql.NullString  `json:"aggregate_id"`
	WorkflowInstanceID uuid.NullUUID   `json:"workflow_instance_id"`
	Timestamp          time.Time       `json:"timestamp"`
	Payload            json.RawMessage `json:"payload"`
	CorrelationID      sql.NullString  `json:"correlation_id"`
	CausationID        sql.NullString  `json:"causation_id"`
	IdempotencyKey     sql.NullString  `json:"idempotency_key"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.TenantID,
		arg.EventID,
		arg.Type,
		arg.Source,
		arg.AggregateID,
		arg.WorkflowInstanceID,
		arg.Timestamp,
		arg.Payload,
		arg.CorrelationID,
		arg.CausationID,
		arg.IdempotencyKey,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventID,
		&i.Type,
		&i.Source,
		&i.AggregateID,
		&i.WorkflowInstanceID,
		&i.Sequence,
		&i.Timestamp,
		&i.Payload,
		&i.CorrelationID,
		&i.CausationID,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const claimInboxEvents = `-- name: ClaimInboxEvents :many
UPDATE event_inbox
SET status = 'PROCESSING', attempt_count = attempt_count + 1, updated_at = NOW()
WHERE id IN (
  SELECT sub.id FROM event_inbox AS sub
  WHERE sub.tenant_id = $1 AND sub.status = 'RECEIVED'
  ORDER BY sub.received_at
  LIMIT $2
)
RETURNING id, tenant_id, idempotency_key, event_type, source, payload, status, attempt_count, received_at, processed_at, created_at, updated_at
`

type ClaimInboxEventsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ClaimInboxEvents(ctx context.Context, arg ClaimInboxEventsParams) ([]EventInbox, error) {
	rows, err := q.db.QueryContext(ctx, claimInboxEvents, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventInbox
	for rows.Next() {
		var i EventInbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.EventType,
			&i.Source,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
UPDATE event_outbox
SET status = 'PENDING', attempt_count = attempt_count + 1, updated_at = NOW()
WHERE id IN (
  SELECT sub.id FROM event_outbox AS sub
  WHERE sub.tenant_id = $1 AND sub.status = 'PENDING'
  ORDER BY sub.created_at
  LIMIT $2
)
RETURNING id, tenant_id, event_id, payload, topic, status, attempt_count, published_at, created_at, updated_at
`

type ClaimOutboxEventsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]EventOutbox, error) {
	rows, err := q.db.QueryContext(ctx, claimOutboxEvents, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventOutbox
	for rows.Next() {
		var i EventOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventID,
			&i.Payload,
			&i.Topic,
			&i.Status,
			&i.AttemptCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEventsFiltered = `-- name: CountEventsFiltered :one
SELECT COUNT(*)
FROM events
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR workflow_instance_id = $2)
  AND ($3::text IS NULL OR type = $3)
  AND ($4::text IS NULL OR source = $4)
  AND ($5::text IS NULL OR correlation_id = $5)
`

type CountEventsFilteredParams struct {
	TenantID           uuid.UUID      `json:"tenant_id"`
	WorkflowInstanceID uuid.NullUUID  `json:"workflow_instance_id"`
	Type               sql.NullString `json:"type"`
	Source             sql.NullString `json:"source"`
	CorrelationID      sql.NullString `json:"correlation_id"`
}

func (q *Queries) CountEventsFiltered(ctx context.Context, arg CountEventsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsFiltered,
		arg.TenantID,
		arg.WorkflowInstanceID,
		arg.Type,
		arg.Source,
		arg.CorrelationID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findEventByID = `-- name: FindEventByID :one
SELECT id, tenant_id, event_id, type, source, aggregate_id, workflow_instance_id, sequence, timestamp, payload, correlation_id, causation_id, idempotency_key, created_at
FROM events
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type FindEventByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindEventByID(ctx context.Context, arg FindEventByIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, findEventByID, arg.ID, arg.TenantID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventID,
		&i.Type,
		&i.Source,
		&i.AggregateID,
		&i.WorkflowInstanceID,
		&i.Sequence,
		&i.Timestamp,
		&i.Payload,
		&i.CorrelationID,
		&i.CausationID,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const findIdempotencyRecord = `-- name: FindIdempotencyRecord :one
SELECT id, tenant_id, idempotency_key, scope, result_status, payload, created_at, updated_at
FROM idempotency_records
WHERE tenant_id = $1 AND idempotency_key = $2
LIMIT 1
`

type FindIdempotencyRecordParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) FindIdempotencyRecord(ctx context.Context, arg FindIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRowContext(ctx, findIdempotencyRecord, arg.TenantID, arg.IdempotencyKey)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Scope,
		&i.ResultStatus,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInboxEvent = `-- name: InsertInboxEvent :one
INSERT INTO event_inbox (tenant_id, idempotency_key, event_type, source, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, idempotency_key, event_type, source, payload, status, attempt_count, received_at, processed_at, created_at, updated_at
`

type InsertInboxEventParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	IdempotencyKey string          `json:"idempotency_key"`
	EventType      string          `json:"event_type"`
	Source         string          `json:"source"`
	Payload        json.RawMessage `json:"payload"`
}

func (q *Queries) InsertInboxEvent(ctx context.Context, arg InsertInboxEventParams) (EventInbox, error) {
	row := q.db.QueryRowContext(ctx, insertInboxEvent,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.EventType,
		arg.Source,
		arg.Payload,
	)
	var i EventInbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.EventType,
		&i.Source,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO event_outbox (tenant_id, event_id, payload, topic)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, event_id, payload, topic, status, attempt_count, published_at, created_at, updated_at
`

type InsertOutboxEventParams struct {
	TenantID uuid.UUID       `json:"tenant_id"`
	EventID  uuid.NullUUID   `json:"event_id"`
	Payload  json.RawMessage `json:"payload"`
	Topic    string          `json:"topic"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (EventOutbox, error) {
	row := q.db.QueryRowContext(ctx, insertOutboxEvent,
		arg.TenantID,
		arg.EventID,
		arg.Payload,
		arg.Topic,
	)
	var i EventOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventID,
		&i.Payload,
		&i.Topic,
		&i.Status,
		&i.AttemptCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsByInstance = `-- name: ListEventsByInstance :many
SELECT id, tenant_id, event_id, type, source, aggregate_id, workflow_instance_id, sequence, timestamp, payload, correlation_id, causation_id, idempotency_key, created_at
FROM events
WHERE workflow_instance_id = $1 AND tenant_id = $2
ORDER BY sequence
`

type ListEventsByInstanceParams struct {
	WorkflowInstanceID uuid.NullUUID `json:"workflow_instance_id"`
	TenantID           uuid.UUID     `json:"tenant_id"`
}

func (q *Queries) ListEventsByInstance(ctx context.Context, arg ListEventsByInstanceParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByInstance, arg.WorkflowInstanceID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventID,
			&i.Type,
			&i.Source,
			&i.AggregateID,
			&i.WorkflowInstanceID,
			&i.Sequence,
			&i.Timestamp,
			&i.Payload,
			&i.CorrelationID,
			&i.CausationID,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTenant = `-- name: ListEventsByTenant :many
SELECT id, tenant_id, event_id, type, source, aggregate_id, workflow_instance_id, sequence, timestamp, payload, correlation_id, causation_id, idempotency_key, created_at
FROM events
WHERE tenant_id = $1
ORDER BY sequence
`

func (q *Queries) ListEventsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventID,
			&i.Type,
			&i.Source,
			&i.AggregateID,
			&i.WorkflowInstanceID,
			&i.Sequence,
			&i.Timestamp,
			&i.Payload,
			&i.CorrelationID,
			&i.CausationID,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsFiltered = `-- name: ListEventsFiltered :many
SELECT id, tenant_id, event_id, type, source, aggregate_id, workflow_instance_id, sequence, timestamp, payload, correlation_id, causation_id, idempotency_key, created_at
FROM events
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR workflow_instance_id = $2)
  AND ($3::text IS NULL OR type = $3)
  AND ($4::text IS NULL OR source = $4)
  AND ($5::text IS NULL OR correlation_id = $5)
ORDER BY sequence DESC
LIMIT $7 OFFSET $6
`

type ListEventsFilteredParams struct {
	TenantID           uuid.UUID      `json:"tenant_id"`
	WorkflowInstanceID uuid.NullUUID  `json:"workflow_instance_id"`
	Type               sql.NullString `json:"type"`
	Source             sql.NullString `json:"source"`
	CorrelationID      sql.NullString `json:"correlation_id"`
	PageOffset         int32          `json:"page_offset"`
	PageSize           int32          `json:"page_size"`
}

func (q *Queries) ListEventsFiltered(ctx context.Context, arg ListEventsFilteredParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsFiltered,
		arg.TenantID,
		arg.WorkflowInstanceID,
		arg.Type,
		arg.Source,
		arg.CorrelationID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventID,
			&i.Type,
			&i.Source,
			&i.AggregateID,
			&i.WorkflowInstanceID,
			&i.Sequence,
			&i.Timestamp,
			&i.Payload,
			&i.CorrelationID,
			&i.CausationID,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxProcessed = `-- name: MarkInboxProcessed :one
UPDATE event_inbox
SET status = 'PROCESSED', processed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, idempotency_key, event_type, source, payload, status, attempt_count, received_at, processed_at, created_at, updated_at
`

type MarkInboxProcessedParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkInboxProcessed(ctx context.Context, arg MarkInboxProcessedParams) (EventInbox, error) {
	row := q.db.QueryRowContext(ctx, markInboxProcessed, arg.ID, arg.TenantID)
	var i EventInbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.EventType,
		&i.Source,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :one
UPDATE event_outbox
SET status = 'PUBLISHED', published_at = NOW(), updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, event_id, payload, topic, status, attempt_count, published_at, created_at, updated_at
`

type MarkOutboxPublishedParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (EventOutbox, error) {
	row := q.db.QueryRowContext(ctx, markOutboxPublished, arg.ID, arg.TenantID)
	var i EventOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventID,
		&i.Payload,
		&i.Topic,
		&i.Status,
		&i.AttemptCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIdempotencyRecord = `-- name: UpsertIdempotencyRecord :one
INSERT INTO idempotency_records (tenant_id, idempotency_key, scope, result_status, payload)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, idempotency_key) DO UPDATE
SET scope = EXCLUDED.scope, result_status = EXCLUDED.result_status, payload = EXCLUDED.payload, updated_at = NOW()
RETURNING id, tenant_id, idempotency_key, scope, result_status, payload, created_at, updated_at
`

type UpsertIdempotencyRecordParams struct {
	TenantID       uuid.UUID             `json:"tenant_id"`
	IdempotencyKey string                `json:"idempotency_key"`
	Scope          string                `json:"scope"`
	ResultStatus   string                `json:"result_status"`
	Payload        pqtype.NullRawMessage `json:"payload"`
}

func (q *Queries) UpsertIdempotencyRecord(ctx context.Context, arg UpsertIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRowContext(ctx, upsertIdempotencyRecord,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.Scope,
		arg.ResultStatus,
		arg.Payload,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Scope,
		&i.ResultStatus,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
