// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO user_identities (user_id, provider, subject_id, auto_provisioned)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, subject_id, auto_provisioned, created_at, updated_at
`

type CreateIdentityParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Provider        string    `json:"provider"`
	SubjectID       string    `json:"subject_id"`
	AutoProvisioned bool      `json:"auto_provisioned"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.SubjectID,
		arg.AutoProvisioned,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.SubjectID,
		&i.AutoProvisioned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findIdentityByProviderSubject = `-- name: FindIdentityByProviderSubject :one

SELECT id, user_id, provider, subject_id, auto_provisioned, created_at, updated_at
FROM user_identities
WHERE provider = $1 AND subject_id = $2
LIMIT 1
`

type FindIdentityByProviderSubjectParams struct {
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
}

// External identity queries (PRD 79). Links an OIDC provider subject to a local
// user and supports auto-provisioning on first login.
func (q *Queries) FindIdentityByProviderSubject(ctx context.Context, arg FindIdentityByProviderSubjectParams) (UserIdentity, error) {
	row := q.db.QueryRowContext(ctx, findIdentityByProviderSubject, arg.Provider, arg.SubjectID)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.SubjectID,
		&i.AutoProvisioned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT id, user_id, provider, subject_id, auto_provisioned, created_at, updated_at
FROM user_identities
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.SubjectID,
			&i.AutoProvisioned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
