// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStateInstance = `-- name: CreateStateInstance :one
INSERT INTO state_instances (tenant_id, workflow_instance_id, workflow_version_id, state_key, state_id, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, workflow_instance_id, workflow_version_id, state_key, state_id, status, version, retry_count, entered_at, expires_at, exited_at, created_at, updated_at
`

type CreateStateInstanceParams struct {
	TenantID           uuid.UUID     `json:"tenant_id"`
	WorkflowInstanceID uuid.UUID     `json:"workflow_instance_id"`
	WorkflowVersionID  uuid.UUID     `json:"workflow_version_id"`
	StateKey           string        `json:"state_key"`
	StateID            uuid.NullUUID `json:"state_id"`
	Status             string        `json:"status"`
}

func (q *Queries) CreateStateInstance(ctx context.Context, arg CreateStateInstanceParams) (StateInstance, error) {
	row := q.db.QueryRowContext(ctx, createStateInstance,
		arg.TenantID,
		arg.WorkflowInstanceID,
		arg.WorkflowVersionID,
		arg.StateKey,
		arg.StateID,
		arg.Status,
	)
	var i StateInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowInstanceID,
		&i.WorkflowVersionID,
		&i.StateKey,
		&i.StateID,
		&i.Status,
		&i.Version,
		&i.RetryCount,
		&i.EnteredAt,
		&i.ExpiresAt,
		&i.ExitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowInstance = `-- name: CreateWorkflowInstance :one
INSERT INTO workflow_instances (tenant_id, workflow_id, workflow_version_id, correlation_key, status, started_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, workflow_id, workflow_version_id, correlation_key, status, version, current_state_instance_id, started_at, completed_at, expires_at, created_at, updated_at
`

type CreateWorkflowInstanceParams struct {
	TenantID          uuid.UUID      `json:"tenant_id"`
	WorkflowID        uuid.UUID      `json:"workflow_id"`
	WorkflowVersionID uuid.UUID      `json:"workflow_version_id"`
	CorrelationKey    sql.NullString `json:"correlation_key"`
	Status            string         `json:"status"`
	StartedAt         sql.NullTime   `json:"started_at"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateWorkflowInstance(ctx context.Context, arg CreateWorkflowInstanceParams) (WorkflowInstance, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowInstance,
		arg.TenantID,
		arg.WorkflowID,
		arg.WorkflowVersionID,
		arg.CorrelationKey,
		arg.Status,
		arg.StartedAt,
		arg.ExpiresAt,
	)
	var i WorkflowInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.CorrelationKey,
		&i.Status,
		&i.Version,
		&i.CurrentStateInstanceID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const exitStateInstance = `-- name: ExitStateInstance :one
UPDATE state_instances
SET status = $4, exited_at = NOW(), version = version + 1, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND version = $3
RETURNING id, tenant_id, workflow_instance_id, workflow_version_id, state_key, state_id, status, version, retry_count, entered_at, expires_at, exited_at, created_at, updated_at
`

type ExitStateInstanceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Version  int32     `json:"version"`
	Status   string    `json:"status"`
}

func (q *Queries) ExitStateInstance(ctx context.Context, arg ExitStateInstanceParams) (StateInstance, error) {
	row := q.db.QueryRowContext(ctx, exitStateInstance,
		arg.ID,
		arg.TenantID,
		arg.Version,
		arg.Status,
	)
	var i StateInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowInstanceID,
		&i.WorkflowVersionID,
		&i.StateKey,
		&i.StateID,
		&i.Status,
		&i.Version,
		&i.RetryCount,
		&i.EnteredAt,
		&i.ExpiresAt,
		&i.ExitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findStateInstanceByID = `-- name: FindStateInstanceByID :one
SELECT id, tenant_id, workflow_instance_id, workflow_version_id, state_key, state_id, status, version, retry_count, entered_at, expires_at, exited_at, created_at, updated_at
FROM state_instances
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type FindStateInstanceByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindStateInstanceByID(ctx context.Context, arg FindStateInstanceByIDParams) (StateInstance, error) {
	row := q.db.QueryRowContext(ctx, findStateInstanceByID, arg.ID, arg.TenantID)
	var i StateInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowInstanceID,
		&i.WorkflowVersionID,
		&i.StateKey,
		&i.StateID,
		&i.Status,
		&i.Version,
		&i.RetryCount,
		&i.EnteredAt,
		&i.ExpiresAt,
		&i.ExitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWorkflowInstanceByID = `-- name: FindWorkflowInstanceByID :one
SELECT id, tenant_id, workflow_id, workflow_version_id, correlation_key, status, version, current_state_instance_id, started_at, completed_at, expires_at, created_at, updated_at
FROM workflow_instances
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type FindWorkflowInstanceByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindWorkflowInstanceByID(ctx context.Context, arg FindWorkflowInstanceByIDParams) (WorkflowInstance, error) {
	row := q.db.QueryRowContext(ctx, findWorkflowInstanceByID, arg.ID, arg.TenantID)
	var i WorkflowInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.CorrelationKey,
		&i.Status,
		&i.Version,
		&i.CurrentStateInstanceID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementWorkflowInstanceVersion = `-- name: IncrementWorkflowInstanceVersion :one
UPDATE workflow_instances
SET version = version + 1, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND version = $3
RETURNING id, tenant_id, workflow_id, workflow_version_id, correlation_key, status, version, current_state_instance_id, started_at, completed_at, expires_at, created_at, updated_at
`

type IncrementWorkflowInstanceVersionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Version  int32     `json:"version"`
}

func (q *Queries) IncrementWorkflowInstanceVersion(ctx context.Context, arg IncrementWorkflowInstanceVersionParams) (WorkflowInstance, error) {
	row := q.db.QueryRowContext(ctx, incrementWorkflowInstanceVersion, arg.ID, arg.TenantID, arg.Version)
	var i WorkflowInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.CorrelationKey,
		&i.Status,
		&i.Version,
		&i.CurrentStateInstanceID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowInstancesByTenant = `-- name: ListWorkflowInstancesByTenant :many
SELECT id, tenant_id, workflow_id, workflow_version_id, correlation_key, status, version, current_state_instance_id, started_at, completed_at, expires_at, created_at, updated_at
FROM workflow_instances
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflowInstancesByTenant(ctx context.Context, tenantID uuid.UUID) ([]WorkflowInstance, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowInstancesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowInstance
	for rows.Next() {
		var i WorkflowInstance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.CorrelationKey,
			&i.Status,
			&i.Version,
			&i.CurrentStateInstanceID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentStateInstance = `-- name: SetCurrentStateInstance :exec
UPDATE workflow_instances
SET current_state_instance_id = $3, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
`

type SetCurrentStateInstanceParams struct {
	ID                     uuid.UUID     `json:"id"`
	TenantID               uuid.UUID     `json:"tenant_id"`
	CurrentStateInstanceID uuid.NullUUID `json:"current_state_instance_id"`
}

func (q *Queries) SetCurrentStateInstance(ctx context.Context, arg SetCurrentStateInstanceParams) error {
	_, err := q.db.ExecContext(ctx, setCurrentStateInstance, arg.ID, arg.TenantID, arg.CurrentStateInstanceID)
	return err
}

const updateStateInstanceRetry = `-- name: UpdateStateInstanceRetry :one
UPDATE state_instances
SET retry_count = retry_count + 1, version = version + 1, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND version = $3
RETURNING id, tenant_id, workflow_instance_id, workflow_version_id, state_key, state_id, status, version, retry_count, entered_at, expires_at, exited_at, created_at, updated_at
`

type UpdateStateInstanceRetryParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Version  int32     `json:"version"`
}

func (q *Queries) UpdateStateInstanceRetry(ctx context.Context, arg UpdateStateInstanceRetryParams) (StateInstance, error) {
	row := q.db.QueryRowContext(ctx, updateStateInstanceRetry, arg.ID, arg.TenantID, arg.Version)
	var i StateInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowInstanceID,
		&i.WorkflowVersionID,
		&i.StateKey,
		&i.StateID,
		&i.Status,
		&i.Version,
		&i.RetryCount,
		&i.EnteredAt,
		&i.ExpiresAt,
		&i.ExitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStateInstanceStatus = `-- name: UpdateStateInstanceStatus :one
UPDATE state_instances
SET status = $4, version = version + 1, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND version = $3
RETURNING id, tenant_id, workflow_instance_id, workflow_version_id, state_key, state_id, status, version, retry_count, entered_at, expires_at, exited_at, created_at, updated_at
`

type UpdateStateInstanceStatusParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Version  int32     `json:"version"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateStateInstanceStatus(ctx context.Context, arg UpdateStateInstanceStatusParams) (StateInstance, error) {
	row := q.db.QueryRowContext(ctx, updateStateInstanceStatus,
		arg.ID,
		arg.TenantID,
		arg.Version,
		arg.Status,
	)
	var i StateInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowInstanceID,
		&i.WorkflowVersionID,
		&i.StateKey,
		&i.StateID,
		&i.Status,
		&i.Version,
		&i.RetryCount,
		&i.EnteredAt,
		&i.ExpiresAt,
		&i.ExitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkflowInstanceStatus = `-- name: UpdateWorkflowInstanceStatus :one
UPDATE workflow_instances
SET status = $4, version = version + 1, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND version = $3
RETURNING id, tenant_id, workflow_id, workflow_version_id, correlation_key, status, version, current_state_instance_id, started_at, completed_at, expires_at, created_at, updated_at
`

type UpdateWorkflowInstanceStatusParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Version  int32     `json:"version"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateWorkflowInstanceStatus(ctx context.Context, arg UpdateWorkflowInstanceStatusParams) (WorkflowInstance, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowInstanceStatus,
		arg.ID,
		arg.TenantID,
		arg.Version,
		arg.Status,
	)
	var i WorkflowInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.CorrelationKey,
		&i.Status,
		&i.Version,
		&i.CurrentStateInstanceID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
