// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intent.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const findRoutableIntent = `-- name: FindRoutableIntent :one
SELECT i.id,
       i.tenant_id,
       i.project_id,
       i.workflow_id,
       i.intent_key,
       i.name,
       i.description,
       i.examples,
       i.created_at,
       i.updated_at,
       w.slug AS workflow_slug
FROM intents i
JOIN projects p
  ON p.id = i.project_id
 AND p.tenant_id = i.tenant_id
JOIN workflows w
  ON w.id = i.workflow_id
 AND w.tenant_id = i.tenant_id
 AND w.project_id = i.project_id
WHERE i.tenant_id = $1
  AND i.project_id = $2
  AND i.intent_key = $3
  AND p.status = 'ACTIVE'
  AND w.status = 'PUBLISHED'
LIMIT 1
`

type FindRoutableIntentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
	IntentKey string    `json:"intent_key"`
}

type FindRoutableIntentRow struct {
	ID           uuid.UUID       `json:"id"`
	TenantID     uuid.UUID       `json:"tenant_id"`
	ProjectID    uuid.UUID       `json:"project_id"`
	WorkflowID   uuid.UUID       `json:"workflow_id"`
	IntentKey    string          `json:"intent_key"`
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	Examples     json.RawMessage `json:"examples"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	WorkflowSlug string          `json:"workflow_slug"`
}

func (q *Queries) FindRoutableIntent(ctx context.Context, arg FindRoutableIntentParams) (FindRoutableIntentRow, error) {
	row := q.db.QueryRowContext(ctx, findRoutableIntent, arg.TenantID, arg.ProjectID, arg.IntentKey)
	var i FindRoutableIntentRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.WorkflowID,
		&i.IntentKey,
		&i.Name,
		&i.Description,
		&i.Examples,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkflowSlug,
	)
	return i, err
}

const listRoutableIntents = `-- name: ListRoutableIntents :many
SELECT i.id,
       i.tenant_id,
       i.project_id,
       i.workflow_id,
       i.intent_key,
       i.name,
       i.description,
       i.examples,
       i.created_at,
       i.updated_at,
       w.slug AS workflow_slug
FROM intents i
JOIN projects p
  ON p.id = i.project_id
 AND p.tenant_id = i.tenant_id
JOIN workflows w
  ON w.id = i.workflow_id
 AND w.tenant_id = i.tenant_id
 AND w.project_id = i.project_id
WHERE i.tenant_id = $1
  AND i.project_id = $2
  AND p.status = 'ACTIVE'
  AND w.status = 'PUBLISHED'
ORDER BY i.created_at ASC, i.intent_key ASC
`

type ListRoutableIntentsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type ListRoutableIntentsRow struct {
	ID           uuid.UUID       `json:"id"`
	TenantID     uuid.UUID       `json:"tenant_id"`
	ProjectID    uuid.UUID       `json:"project_id"`
	WorkflowID   uuid.UUID       `json:"workflow_id"`
	IntentKey    string          `json:"intent_key"`
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	Examples     json.RawMessage `json:"examples"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	WorkflowSlug string          `json:"workflow_slug"`
}

func (q *Queries) ListRoutableIntents(ctx context.Context, arg ListRoutableIntentsParams) ([]ListRoutableIntentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoutableIntents, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutableIntentsRow
	for rows.Next() {
		var i ListRoutableIntentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.WorkflowID,
			&i.IntentKey,
			&i.Name,
			&i.Description,
			&i.Examples,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkflowSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIntent = `-- name: UpsertIntent :one
INSERT INTO intents (
  tenant_id,
  project_id,
  workflow_id,
  intent_key,
  name,
  description,
  examples
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, project_id, intent_key)
DO UPDATE SET
  workflow_id = EXCLUDED.workflow_id,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  examples = EXCLUDED.examples,
  updated_at = NOW()
RETURNING id,
          tenant_id,
          project_id,
          workflow_id,
          intent_key,
          name,
          description,
          examples,
          created_at,
          updated_at
`

type UpsertIntentParams struct {
	TenantID    uuid.UUID       `json:"tenant_id"`
	ProjectID   uuid.UUID       `json:"project_id"`
	WorkflowID  uuid.UUID       `json:"workflow_id"`
	IntentKey   string          `json:"intent_key"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Examples    json.RawMessage `json:"examples"`
}

func (q *Queries) UpsertIntent(ctx context.Context, arg UpsertIntentParams) (Intent, error) {
	row := q.db.QueryRowContext(ctx, upsertIntent,
		arg.TenantID,
		arg.ProjectID,
		arg.WorkflowID,
		arg.IntentKey,
		arg.Name,
		arg.Description,
		arg.Examples,
	)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.WorkflowID,
		&i.IntentKey,
		&i.Name,
		&i.Description,
		&i.Examples,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
