// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_connection.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createMCPConnection = `-- name: CreateMCPConnection :one
INSERT INTO mcp_connections (
  tenant_id, project_id, name, alias, transport, endpoint, stdio_profile,
  stdio_args, auth_type, credential_reference, credential_status, status,
  oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, timeout_ms, max_concurrency,
  rate_limit_per_second, rate_limit_burst, retry_max, circuit_failure_threshold,
  circuit_recovery_seconds, created_by, updated_by
)
VALUES (
  $1, $2, $3, $4, $5, NULLIF($6, ''), NULLIF($7, ''), $8, $9,
  NULLIF($10, ''), $11, $12, NULLIF($13, ''), NULLIF($14, ''), NULLIF($15, ''),
  NULLIF($16, ''), $17, NULLIF($18, ''), $19, $20, $21, $22, $23, $24, $25, $26, $26
)
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type CreateMCPConnectionParams struct {
	TenantID                uuid.UUID       `json:"tenant_id"`
	ProjectID               uuid.UUID       `json:"project_id"`
	Name                    string          `json:"name"`
	Alias                   string          `json:"alias"`
	Transport               string          `json:"transport"`
	Column6                 interface{}     `json:"column_6"`
	Column7                 interface{}     `json:"column_7"`
	StdioArgs               json.RawMessage `json:"stdio_args"`
	AuthType                string          `json:"auth_type"`
	Column10                interface{}     `json:"column_10"`
	CredentialStatus        string          `json:"credential_status"`
	Status                  string          `json:"status"`
	Column13                interface{}     `json:"column_13"`
	Column14                interface{}     `json:"column_14"`
	Column15                interface{}     `json:"column_15"`
	Column16                interface{}     `json:"column_16"`
	OauthScopes             json.RawMessage `json:"oauth_scopes"`
	Column18                interface{}     `json:"column_18"`
	TimeoutMs               int32           `json:"timeout_ms"`
	MaxConcurrency          int32           `json:"max_concurrency"`
	RateLimitPerSecond      float64         `json:"rate_limit_per_second"`
	RateLimitBurst          int32           `json:"rate_limit_burst"`
	RetryMax                int32           `json:"retry_max"`
	CircuitFailureThreshold int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds  int32           `json:"circuit_recovery_seconds"`
	CreatedBy               string          `json:"created_by"`
}

type CreateMCPConnectionRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) CreateMCPConnection(ctx context.Context, arg CreateMCPConnectionParams) (CreateMCPConnectionRow, error) {
	row := q.db.QueryRowContext(ctx, createMCPConnection,
		arg.TenantID,
		arg.ProjectID,
		arg.Name,
		arg.Alias,
		arg.Transport,
		arg.Column6,
		arg.Column7,
		arg.StdioArgs,
		arg.AuthType,
		arg.Column10,
		arg.CredentialStatus,
		arg.Status,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
		arg.OauthScopes,
		arg.Column18,
		arg.TimeoutMs,
		arg.MaxConcurrency,
		arg.RateLimitPerSecond,
		arg.RateLimitBurst,
		arg.RetryMax,
		arg.CircuitFailureThreshold,
		arg.CircuitRecoverySeconds,
		arg.CreatedBy,
	)
	var i CreateMCPConnectionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPConnection = `-- name: DeleteMCPConnection :exec
DELETE FROM mcp_connections
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
`

type DeleteMCPConnectionParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteMCPConnection(ctx context.Context, arg DeleteMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteMCPConnection, arg.ID, arg.TenantID, arg.ProjectID)
	return err
}

const disconnectMCPConnectionOAuth = `-- name: DisconnectMCPConnectionOAuth :one
UPDATE mcp_connections
SET credential_reference = NULL,
    oauth_access_token_reference = NULL,
    oauth_refresh_token_reference = NULL,
    oauth_expires_at = NULL,
    oauth_status = 'disconnected',
    credential_status = 'action_required',
    updated_by = $4,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type DisconnectMCPConnectionOAuthParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
	UpdatedBy string    `json:"updated_by"`
}

type DisconnectMCPConnectionOAuthRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) DisconnectMCPConnectionOAuth(ctx context.Context, arg DisconnectMCPConnectionOAuthParams) (DisconnectMCPConnectionOAuthRow, error) {
	row := q.db.QueryRowContext(ctx, disconnectMCPConnectionOAuth,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.UpdatedBy,
	)
	var i DisconnectMCPConnectionOAuthRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMCPConnectionByID = `-- name: FindMCPConnectionByID :one
SELECT id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
FROM mcp_connections
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
LIMIT 1
`

type FindMCPConnectionByIDParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type FindMCPConnectionByIDRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) FindMCPConnectionByID(ctx context.Context, arg FindMCPConnectionByIDParams) (FindMCPConnectionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findMCPConnectionByID, arg.ID, arg.TenantID, arg.ProjectID)
	var i FindMCPConnectionByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPConnectionsByProject = `-- name: ListMCPConnectionsByProject :many
SELECT id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
FROM mcp_connections
WHERE tenant_id = $1 AND project_id = $2
ORDER BY created_at DESC, alias ASC
`

type ListMCPConnectionsByProjectParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type ListMCPConnectionsByProjectRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) ListMCPConnectionsByProject(ctx context.Context, arg ListMCPConnectionsByProjectParams) ([]ListMCPConnectionsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listMCPConnectionsByProject, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPConnectionsByProjectRow
	for rows.Next() {
		var i ListMCPConnectionsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Name,
			&i.Alias,
			&i.Transport,
			&i.Endpoint,
			&i.StdioProfile,
			&i.StdioArgs,
			&i.AuthType,
			&i.CredentialReference,
			&i.CredentialStatus,
			&i.Status,
			&i.OauthAuthorizationEndpoint,
			&i.OauthTokenEndpoint,
			&i.OauthClientID,
			&i.OauthClientSecretReference,
			&i.OauthScopes,
			&i.OauthRedirectUri,
			&i.OauthAccessTokenReference,
			&i.OauthRefreshTokenReference,
			&i.OauthExpiresAt,
			&i.OauthStatus,
			&i.HealthStatus,
			&i.HealthReason,
			&i.LastSuccessAt,
			&i.ConsecutiveFailures,
			&i.CircuitOpenedAt,
			&i.TimeoutMs,
			&i.MaxConcurrency,
			&i.RateLimitPerSecond,
			&i.RateLimitBurst,
			&i.RetryMax,
			&i.CircuitFailureThreshold,
			&i.CircuitRecoverySeconds,
			&i.LastTestStatus,
			&i.LastTestErrorCode,
			&i.LastTestedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMCPConnectionHealth = `-- name: RecordMCPConnectionHealth :one
UPDATE mcp_connections
SET health_status = $4,
    health_reason = NULLIF($5, ''),
    last_success_at = COALESCE($6, last_success_at),
    consecutive_failures = $7,
    circuit_opened_at = $8,
    updated_by = $9,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type RecordMCPConnectionHealthParams struct {
	ID                  uuid.UUID    `json:"id"`
	TenantID            uuid.UUID    `json:"tenant_id"`
	ProjectID           uuid.UUID    `json:"project_id"`
	HealthStatus        string       `json:"health_status"`
	Column5             interface{}  `json:"column_5"`
	LastSuccessAt       sql.NullTime `json:"last_success_at"`
	ConsecutiveFailures int32        `json:"consecutive_failures"`
	CircuitOpenedAt     sql.NullTime `json:"circuit_opened_at"`
	UpdatedBy           string       `json:"updated_by"`
}

type RecordMCPConnectionHealthRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) RecordMCPConnectionHealth(ctx context.Context, arg RecordMCPConnectionHealthParams) (RecordMCPConnectionHealthRow, error) {
	row := q.db.QueryRowContext(ctx, recordMCPConnectionHealth,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.HealthStatus,
		arg.Column5,
		arg.LastSuccessAt,
		arg.ConsecutiveFailures,
		arg.CircuitOpenedAt,
		arg.UpdatedBy,
	)
	var i RecordMCPConnectionHealthRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordMCPConnectionTest = `-- name: RecordMCPConnectionTest :one
UPDATE mcp_connections
SET last_test_status = $4,
    last_test_error_code = NULLIF($5, ''),
    last_tested_at = NOW(),
    updated_by = $6,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type RecordMCPConnectionTestParams struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	ProjectID      uuid.UUID   `json:"project_id"`
	LastTestStatus string      `json:"last_test_status"`
	Column5        interface{} `json:"column_5"`
	UpdatedBy      string      `json:"updated_by"`
}

type RecordMCPConnectionTestRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) RecordMCPConnectionTest(ctx context.Context, arg RecordMCPConnectionTestParams) (RecordMCPConnectionTestRow, error) {
	row := q.db.QueryRowContext(ctx, recordMCPConnectionTest,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.LastTestStatus,
		arg.Column5,
		arg.UpdatedBy,
	)
	var i RecordMCPConnectionTestRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetMCPConnectionHealth = `-- name: ResetMCPConnectionHealth :one
UPDATE mcp_connections
SET health_status = 'unknown', health_reason = NULL, consecutive_failures = 0,
    circuit_opened_at = NULL, updated_by = $4, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type ResetMCPConnectionHealthParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
	UpdatedBy string    `json:"updated_by"`
}

type ResetMCPConnectionHealthRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) ResetMCPConnectionHealth(ctx context.Context, arg ResetMCPConnectionHealthParams) (ResetMCPConnectionHealthRow, error) {
	row := q.db.QueryRowContext(ctx, resetMCPConnectionHealth,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.UpdatedBy,
	)
	var i ResetMCPConnectionHealthRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMCPConnection = `-- name: UpdateMCPConnection :one
UPDATE mcp_connections
SET name = $4,
    alias = $5,
    transport = $6,
    endpoint = NULLIF($7, ''),
    stdio_profile = NULLIF($8, ''),
    stdio_args = $9,
    auth_type = $10,
    credential_reference = CASE WHEN $11 IS NULL THEN NULL WHEN $11 = '' THEN credential_reference ELSE $11 END,
    credential_status = $12,
    oauth_authorization_endpoint = NULLIF($13, ''),
    oauth_token_endpoint = NULLIF($14, ''),
    oauth_client_id = NULLIF($15, ''),
    oauth_client_secret_reference = NULLIF($16, ''),
    oauth_scopes = $17,
    oauth_redirect_uri = NULLIF($18, ''),
    timeout_ms = $19,
    max_concurrency = $20,
    rate_limit_per_second = $21,
    rate_limit_burst = $22,
    retry_max = $23,
    circuit_failure_threshold = $24,
    circuit_recovery_seconds = $25,
    updated_by = $26,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type UpdateMCPConnectionParams struct {
	ID                      uuid.UUID       `json:"id"`
	TenantID                uuid.UUID       `json:"tenant_id"`
	ProjectID               uuid.UUID       `json:"project_id"`
	Name                    string          `json:"name"`
	Alias                   string          `json:"alias"`
	Transport               string          `json:"transport"`
	Column7                 interface{}     `json:"column_7"`
	Column8                 interface{}     `json:"column_8"`
	StdioArgs               json.RawMessage `json:"stdio_args"`
	AuthType                string          `json:"auth_type"`
	CredentialReference     sql.NullString  `json:"credential_reference"`
	CredentialStatus        string          `json:"credential_status"`
	Column13                interface{}     `json:"column_13"`
	Column14                interface{}     `json:"column_14"`
	Column15                interface{}     `json:"column_15"`
	Column16                interface{}     `json:"column_16"`
	OauthScopes             json.RawMessage `json:"oauth_scopes"`
	Column18                interface{}     `json:"column_18"`
	TimeoutMs               int32           `json:"timeout_ms"`
	MaxConcurrency          int32           `json:"max_concurrency"`
	RateLimitPerSecond      float64         `json:"rate_limit_per_second"`
	RateLimitBurst          int32           `json:"rate_limit_burst"`
	RetryMax                int32           `json:"retry_max"`
	CircuitFailureThreshold int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds  int32           `json:"circuit_recovery_seconds"`
	UpdatedBy               string          `json:"updated_by"`
}

type UpdateMCPConnectionRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateMCPConnection(ctx context.Context, arg UpdateMCPConnectionParams) (UpdateMCPConnectionRow, error) {
	row := q.db.QueryRowContext(ctx, updateMCPConnection,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.Name,
		arg.Alias,
		arg.Transport,
		arg.Column7,
		arg.Column8,
		arg.StdioArgs,
		arg.AuthType,
		arg.CredentialReference,
		arg.CredentialStatus,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
		arg.OauthScopes,
		arg.Column18,
		arg.TimeoutMs,
		arg.MaxConcurrency,
		arg.RateLimitPerSecond,
		arg.RateLimitBurst,
		arg.RetryMax,
		arg.CircuitFailureThreshold,
		arg.CircuitRecoverySeconds,
		arg.UpdatedBy,
	)
	var i UpdateMCPConnectionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMCPConnectionCredential = `-- name: UpdateMCPConnectionCredential :one
UPDATE mcp_connections
SET credential_reference = $4,
    credential_status = $5,
    updated_by = $6,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type UpdateMCPConnectionCredentialParams struct {
	ID                  uuid.UUID      `json:"id"`
	TenantID            uuid.UUID      `json:"tenant_id"`
	ProjectID           uuid.UUID      `json:"project_id"`
	CredentialReference sql.NullString `json:"credential_reference"`
	CredentialStatus    string         `json:"credential_status"`
	UpdatedBy           string         `json:"updated_by"`
}

type UpdateMCPConnectionCredentialRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateMCPConnectionCredential(ctx context.Context, arg UpdateMCPConnectionCredentialParams) (UpdateMCPConnectionCredentialRow, error) {
	row := q.db.QueryRowContext(ctx, updateMCPConnectionCredential,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.CredentialReference,
		arg.CredentialStatus,
		arg.UpdatedBy,
	)
	var i UpdateMCPConnectionCredentialRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMCPConnectionOAuth = `-- name: UpdateMCPConnectionOAuth :one
UPDATE mcp_connections
SET credential_reference = $4,
    oauth_access_token_reference = $4,
    oauth_refresh_token_reference = $5,
    credential_status = $6,
    oauth_status = $7,
    oauth_expires_at = $8,
    updated_by = $9,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type UpdateMCPConnectionOAuthParams struct {
	ID                         uuid.UUID      `json:"id"`
	TenantID                   uuid.UUID      `json:"tenant_id"`
	ProjectID                  uuid.UUID      `json:"project_id"`
	CredentialReference        sql.NullString `json:"credential_reference"`
	OauthRefreshTokenReference sql.NullString `json:"oauth_refresh_token_reference"`
	CredentialStatus           string         `json:"credential_status"`
	OauthStatus                string         `json:"oauth_status"`
	OauthExpiresAt             sql.NullTime   `json:"oauth_expires_at"`
	UpdatedBy                  string         `json:"updated_by"`
}

type UpdateMCPConnectionOAuthRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateMCPConnectionOAuth(ctx context.Context, arg UpdateMCPConnectionOAuthParams) (UpdateMCPConnectionOAuthRow, error) {
	row := q.db.QueryRowContext(ctx, updateMCPConnectionOAuth,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.CredentialReference,
		arg.OauthRefreshTokenReference,
		arg.CredentialStatus,
		arg.OauthStatus,
		arg.OauthExpiresAt,
		arg.UpdatedBy,
	)
	var i UpdateMCPConnectionOAuthRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMCPConnectionStatus = `-- name: UpdateMCPConnectionStatus :one
UPDATE mcp_connections
SET status = $4,
    last_test_status = CASE WHEN $4 = 'disabled' THEN 'disabled' ELSE last_test_status END,
    updated_by = $5,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, oauth_authorization_endpoint, oauth_token_endpoint, oauth_client_id,
  oauth_client_secret_reference, oauth_scopes, oauth_redirect_uri, oauth_access_token_reference,
  oauth_refresh_token_reference, oauth_expires_at, oauth_status, health_status,
  health_reason, last_success_at, consecutive_failures, circuit_opened_at,
  timeout_ms, max_concurrency, rate_limit_per_second, rate_limit_burst,
  retry_max, circuit_failure_threshold, circuit_recovery_seconds,
  last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type UpdateMCPConnectionStatusParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
	UpdatedBy string    `json:"updated_by"`
}

type UpdateMCPConnectionStatusRow struct {
	ID                         uuid.UUID       `json:"id"`
	TenantID                   uuid.UUID       `json:"tenant_id"`
	ProjectID                  uuid.UUID       `json:"project_id"`
	Name                       string          `json:"name"`
	Alias                      string          `json:"alias"`
	Transport                  string          `json:"transport"`
	Endpoint                   sql.NullString  `json:"endpoint"`
	StdioProfile               sql.NullString  `json:"stdio_profile"`
	StdioArgs                  json.RawMessage `json:"stdio_args"`
	AuthType                   string          `json:"auth_type"`
	CredentialReference        sql.NullString  `json:"credential_reference"`
	CredentialStatus           string          `json:"credential_status"`
	Status                     string          `json:"status"`
	OauthAuthorizationEndpoint sql.NullString  `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString  `json:"oauth_token_endpoint"`
	OauthClientID              sql.NullString  `json:"oauth_client_id"`
	OauthClientSecretReference sql.NullString  `json:"oauth_client_secret_reference"`
	OauthScopes                json.RawMessage `json:"oauth_scopes"`
	OauthRedirectUri           sql.NullString  `json:"oauth_redirect_uri"`
	OauthAccessTokenReference  sql.NullString  `json:"oauth_access_token_reference"`
	OauthRefreshTokenReference sql.NullString  `json:"oauth_refresh_token_reference"`
	OauthExpiresAt             sql.NullTime    `json:"oauth_expires_at"`
	OauthStatus                string          `json:"oauth_status"`
	HealthStatus               string          `json:"health_status"`
	HealthReason               sql.NullString  `json:"health_reason"`
	LastSuccessAt              sql.NullTime    `json:"last_success_at"`
	ConsecutiveFailures        int32           `json:"consecutive_failures"`
	CircuitOpenedAt            sql.NullTime    `json:"circuit_opened_at"`
	TimeoutMs                  int32           `json:"timeout_ms"`
	MaxConcurrency             int32           `json:"max_concurrency"`
	RateLimitPerSecond         float64         `json:"rate_limit_per_second"`
	RateLimitBurst             int32           `json:"rate_limit_burst"`
	RetryMax                   int32           `json:"retry_max"`
	CircuitFailureThreshold    int32           `json:"circuit_failure_threshold"`
	CircuitRecoverySeconds     int32           `json:"circuit_recovery_seconds"`
	LastTestStatus             string          `json:"last_test_status"`
	LastTestErrorCode          sql.NullString  `json:"last_test_error_code"`
	LastTestedAt               sql.NullTime    `json:"last_tested_at"`
	CreatedBy                  string          `json:"created_by"`
	UpdatedBy                  string          `json:"updated_by"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateMCPConnectionStatus(ctx context.Context, arg UpdateMCPConnectionStatusParams) (UpdateMCPConnectionStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateMCPConnectionStatus,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.Status,
		arg.UpdatedBy,
	)
	var i UpdateMCPConnectionStatusRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthClientID,
		&i.OauthClientSecretReference,
		&i.OauthScopes,
		&i.OauthRedirectUri,
		&i.OauthAccessTokenReference,
		&i.OauthRefreshTokenReference,
		&i.OauthExpiresAt,
		&i.OauthStatus,
		&i.HealthStatus,
		&i.HealthReason,
		&i.LastSuccessAt,
		&i.ConsecutiveFailures,
		&i.CircuitOpenedAt,
		&i.TimeoutMs,
		&i.MaxConcurrency,
		&i.RateLimitPerSecond,
		&i.RateLimitBurst,
		&i.RetryMax,
		&i.CircuitFailureThreshold,
		&i.CircuitRecoverySeconds,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
