// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_connection.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createMCPConnection = `-- name: CreateMCPConnection :one
INSERT INTO mcp_connections (
  tenant_id, project_id, name, alias, transport, endpoint, stdio_profile,
  stdio_args, auth_type, credential_reference, credential_status, status,
  created_by, updated_by
)
VALUES (
  $1, $2, $3, $4, $5, NULLIF($6, ''), NULLIF($7, ''), $8, $9,
  NULLIF($10, ''), $11, $12, $13, $13
)
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type CreateMCPConnectionParams struct {
	TenantID         uuid.UUID       `json:"tenant_id"`
	ProjectID        uuid.UUID       `json:"project_id"`
	Name             string          `json:"name"`
	Alias            string          `json:"alias"`
	Transport        string          `json:"transport"`
	Column6          interface{}     `json:"column_6"`
	Column7          interface{}     `json:"column_7"`
	StdioArgs        json.RawMessage `json:"stdio_args"`
	AuthType         string          `json:"auth_type"`
	Column10         interface{}     `json:"column_10"`
	CredentialStatus string          `json:"credential_status"`
	Status           string          `json:"status"`
	CreatedBy        string          `json:"created_by"`
}

func (q *Queries) CreateMCPConnection(ctx context.Context, arg CreateMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, createMCPConnection,
		arg.TenantID,
		arg.ProjectID,
		arg.Name,
		arg.Alias,
		arg.Transport,
		arg.Column6,
		arg.Column7,
		arg.StdioArgs,
		arg.AuthType,
		arg.Column10,
		arg.CredentialStatus,
		arg.Status,
		arg.CreatedBy,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPConnection = `-- name: DeleteMCPConnection :exec
DELETE FROM mcp_connections
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
`

type DeleteMCPConnectionParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteMCPConnection(ctx context.Context, arg DeleteMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteMCPConnection, arg.ID, arg.TenantID, arg.ProjectID)
	return err
}

const findMCPConnectionByID = `-- name: FindMCPConnectionByID :one
SELECT id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
FROM mcp_connections
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
LIMIT 1
`

type FindMCPConnectionByIDParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) FindMCPConnectionByID(ctx context.Context, arg FindMCPConnectionByIDParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, findMCPConnectionByID, arg.ID, arg.TenantID, arg.ProjectID)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPConnectionsByProject = `-- name: ListMCPConnectionsByProject :many
SELECT id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
FROM mcp_connections
WHERE tenant_id = $1 AND project_id = $2
ORDER BY created_at DESC, alias ASC
`

type ListMCPConnectionsByProjectParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) ListMCPConnectionsByProject(ctx context.Context, arg ListMCPConnectionsByProjectParams) ([]McpConnection, error) {
	rows, err := q.db.QueryContext(ctx, listMCPConnectionsByProject, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpConnection
	for rows.Next() {
		var i McpConnection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Name,
			&i.Alias,
			&i.Transport,
			&i.Endpoint,
			&i.StdioProfile,
			&i.StdioArgs,
			&i.AuthType,
			&i.CredentialReference,
			&i.CredentialStatus,
			&i.Status,
			&i.LastTestStatus,
			&i.LastTestErrorCode,
			&i.LastTestedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMCPConnectionTest = `-- name: RecordMCPConnectionTest :one
UPDATE mcp_connections
SET last_test_status = $4,
    last_test_error_code = NULLIF($5, ''),
    last_tested_at = NOW(),
    updated_by = $6,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type RecordMCPConnectionTestParams struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	ProjectID      uuid.UUID   `json:"project_id"`
	LastTestStatus string      `json:"last_test_status"`
	Column5        interface{} `json:"column_5"`
	UpdatedBy      string      `json:"updated_by"`
}

func (q *Queries) RecordMCPConnectionTest(ctx context.Context, arg RecordMCPConnectionTestParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, recordMCPConnectionTest,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.LastTestStatus,
		arg.Column5,
		arg.UpdatedBy,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMCPConnection = `-- name: UpdateMCPConnection :one
UPDATE mcp_connections
SET name = $4,
    alias = $5,
    transport = $6,
    endpoint = NULLIF($7, ''),
    stdio_profile = NULLIF($8, ''),
    stdio_args = $9,
    auth_type = $10,
    credential_reference = CASE WHEN $11 IS NULL THEN NULL WHEN $11 = '' THEN credential_reference ELSE $11 END,
    credential_status = $12,
    updated_by = $13,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type UpdateMCPConnectionParams struct {
	ID                  uuid.UUID       `json:"id"`
	TenantID            uuid.UUID       `json:"tenant_id"`
	ProjectID           uuid.UUID       `json:"project_id"`
	Name                string          `json:"name"`
	Alias               string          `json:"alias"`
	Transport           string          `json:"transport"`
	Column7             interface{}     `json:"column_7"`
	Column8             interface{}     `json:"column_8"`
	StdioArgs           json.RawMessage `json:"stdio_args"`
	AuthType            string          `json:"auth_type"`
	CredentialReference sql.NullString  `json:"credential_reference"`
	CredentialStatus    string          `json:"credential_status"`
	UpdatedBy           string          `json:"updated_by"`
}

func (q *Queries) UpdateMCPConnection(ctx context.Context, arg UpdateMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, updateMCPConnection,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.Name,
		arg.Alias,
		arg.Transport,
		arg.Column7,
		arg.Column8,
		arg.StdioArgs,
		arg.AuthType,
		arg.CredentialReference,
		arg.CredentialStatus,
		arg.UpdatedBy,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMCPConnectionStatus = `-- name: UpdateMCPConnectionStatus :one
UPDATE mcp_connections
SET status = $4,
    last_test_status = CASE WHEN $4 = 'disabled' THEN 'disabled' ELSE last_test_status END,
    updated_by = $5,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
RETURNING id, tenant_id, project_id, name, alias, transport, endpoint,
  stdio_profile, stdio_args, auth_type, credential_reference, credential_status,
  status, last_test_status, last_test_error_code, last_tested_at, created_by,
  updated_by, created_at, updated_at
`

type UpdateMCPConnectionStatusParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
	UpdatedBy string    `json:"updated_by"`
}

func (q *Queries) UpdateMCPConnectionStatus(ctx context.Context, arg UpdateMCPConnectionStatusParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, updateMCPConnectionStatus,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.Status,
		arg.UpdatedBy,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Alias,
		&i.Transport,
		&i.Endpoint,
		&i.StdioProfile,
		&i.StdioArgs,
		&i.AuthType,
		&i.CredentialReference,
		&i.CredentialStatus,
		&i.Status,
		&i.LastTestStatus,
		&i.LastTestErrorCode,
		&i.LastTestedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
