// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_tool_catalog.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createMCPDiscoveryRun = `-- name: CreateMCPDiscoveryRun :one
INSERT INTO mcp_discovery_runs (
  tenant_id, project_id, connection_id, status, tool_count,
  catalog_fingerprint, error_code, started_at, completed_at, created_by
)
VALUES ($1, $2, $3, $4, $5, NULLIF($6, ''), NULLIF($7, ''), $8, $9, $10)
RETURNING id, tenant_id, project_id, connection_id, status, tool_count,
  catalog_fingerprint, error_code, started_at, completed_at, created_by
`

type CreateMCPDiscoveryRunParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	ProjectID    uuid.UUID   `json:"project_id"`
	ConnectionID uuid.UUID   `json:"connection_id"`
	Status       string      `json:"status"`
	ToolCount    int32       `json:"tool_count"`
	Column6      interface{} `json:"column_6"`
	Column7      interface{} `json:"column_7"`
	StartedAt    time.Time   `json:"started_at"`
	CompletedAt  time.Time   `json:"completed_at"`
	CreatedBy    string      `json:"created_by"`
}

func (q *Queries) CreateMCPDiscoveryRun(ctx context.Context, arg CreateMCPDiscoveryRunParams) (McpDiscoveryRun, error) {
	row := q.db.QueryRowContext(ctx, createMCPDiscoveryRun,
		arg.TenantID,
		arg.ProjectID,
		arg.ConnectionID,
		arg.Status,
		arg.ToolCount,
		arg.Column6,
		arg.Column7,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CreatedBy,
	)
	var i McpDiscoveryRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.Status,
		&i.ToolCount,
		&i.CatalogFingerprint,
		&i.ErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLastSuccessfulMCPDiscoveryRun = `-- name: GetLastSuccessfulMCPDiscoveryRun :one
SELECT id, tenant_id, project_id, connection_id, status, tool_count,
  catalog_fingerprint, error_code, started_at, completed_at, created_by
FROM mcp_discovery_runs
WHERE tenant_id = $1 AND project_id = $2 AND connection_id = $3
  AND status = 'succeeded'
ORDER BY completed_at DESC
LIMIT 1
`

type GetLastSuccessfulMCPDiscoveryRunParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

func (q *Queries) GetLastSuccessfulMCPDiscoveryRun(ctx context.Context, arg GetLastSuccessfulMCPDiscoveryRunParams) (McpDiscoveryRun, error) {
	row := q.db.QueryRowContext(ctx, getLastSuccessfulMCPDiscoveryRun, arg.TenantID, arg.ProjectID, arg.ConnectionID)
	var i McpDiscoveryRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.Status,
		&i.ToolCount,
		&i.CatalogFingerprint,
		&i.ErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLatestMCPDiscoveryRun = `-- name: GetLatestMCPDiscoveryRun :one
SELECT id, tenant_id, project_id, connection_id, status, tool_count,
  catalog_fingerprint, error_code, started_at, completed_at, created_by
FROM mcp_discovery_runs
WHERE tenant_id = $1 AND project_id = $2 AND connection_id = $3
ORDER BY completed_at DESC
LIMIT 1
`

type GetLatestMCPDiscoveryRunParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

func (q *Queries) GetLatestMCPDiscoveryRun(ctx context.Context, arg GetLatestMCPDiscoveryRunParams) (McpDiscoveryRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestMCPDiscoveryRun, arg.TenantID, arg.ProjectID, arg.ConnectionID)
	var i McpDiscoveryRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.Status,
		&i.ToolCount,
		&i.CatalogFingerprint,
		&i.ErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listMCPDiscoveredTools = `-- name: ListMCPDiscoveredTools :many
SELECT id, tenant_id, project_id, connection_id, tool_name, title, description,
  input_schema, annotations, fingerprint, enabled, availability, drift_status,
  first_seen_at, last_seen_at, removed_at, discovery_run_id, created_at, updated_at
FROM mcp_discovered_tools
WHERE tenant_id = $1 AND project_id = $2 AND connection_id = $3
ORDER BY availability ASC, tool_name ASC
`

type ListMCPDiscoveredToolsParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

func (q *Queries) ListMCPDiscoveredTools(ctx context.Context, arg ListMCPDiscoveredToolsParams) ([]McpDiscoveredTool, error) {
	rows, err := q.db.QueryContext(ctx, listMCPDiscoveredTools, arg.TenantID, arg.ProjectID, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpDiscoveredTool
	for rows.Next() {
		var i McpDiscoveredTool
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.ConnectionID,
			&i.ToolName,
			&i.Title,
			&i.Description,
			&i.InputSchema,
			&i.Annotations,
			&i.Fingerprint,
			&i.Enabled,
			&i.Availability,
			&i.DriftStatus,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.RemovedAt,
			&i.DiscoveryRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMCPDiscoveredToolsRemoved = `-- name: MarkMCPDiscoveredToolsRemoved :exec
UPDATE mcp_discovered_tools
SET availability = 'removed',
    drift_status = 'removed',
    removed_at = COALESCE(removed_at, NOW()),
    updated_at = NOW()
WHERE tenant_id = $1 AND project_id = $2 AND connection_id = $3
  AND availability <> 'removed'
`

type MarkMCPDiscoveredToolsRemovedParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

func (q *Queries) MarkMCPDiscoveredToolsRemoved(ctx context.Context, arg MarkMCPDiscoveredToolsRemovedParams) error {
	_, err := q.db.ExecContext(ctx, markMCPDiscoveredToolsRemoved, arg.TenantID, arg.ProjectID, arg.ConnectionID)
	return err
}

const setMCPDiscoveredToolEnabled = `-- name: SetMCPDiscoveredToolEnabled :one
UPDATE mcp_discovered_tools
SET enabled = $4,
    updated_at = NOW()
WHERE tenant_id = $1 AND project_id = $2 AND connection_id = $3 AND tool_name = $5
RETURNING id, tenant_id, project_id, connection_id, tool_name, title, description,
  input_schema, annotations, fingerprint, enabled, availability, drift_status,
  first_seen_at, last_seen_at, removed_at, discovery_run_id, created_at, updated_at
`

type SetMCPDiscoveredToolEnabledParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	Enabled      bool      `json:"enabled"`
	ToolName     string    `json:"tool_name"`
}

func (q *Queries) SetMCPDiscoveredToolEnabled(ctx context.Context, arg SetMCPDiscoveredToolEnabledParams) (McpDiscoveredTool, error) {
	row := q.db.QueryRowContext(ctx, setMCPDiscoveredToolEnabled,
		arg.TenantID,
		arg.ProjectID,
		arg.ConnectionID,
		arg.Enabled,
		arg.ToolName,
	)
	var i McpDiscoveredTool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.ToolName,
		&i.Title,
		&i.Description,
		&i.InputSchema,
		&i.Annotations,
		&i.Fingerprint,
		&i.Enabled,
		&i.Availability,
		&i.DriftStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.RemovedAt,
		&i.DiscoveryRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMCPDiscoveredTool = `-- name: UpsertMCPDiscoveredTool :one
INSERT INTO mcp_discovered_tools (
  tenant_id, project_id, connection_id, tool_name, title, description,
  input_schema, annotations, fingerprint, availability, drift_status,
  last_seen_at, removed_at, discovery_run_id
)
VALUES ($1, $2, $3, $4, NULLIF($5, ''), $6, $7, $8, $9, 'present', 'new', NOW(), NULL, $10)
ON CONFLICT (connection_id, tool_name) DO UPDATE
SET title = EXCLUDED.title,
    description = EXCLUDED.description,
    input_schema = EXCLUDED.input_schema,
    annotations = EXCLUDED.annotations,
    drift_status = CASE
      WHEN mcp_discovered_tools.fingerprint = EXCLUDED.fingerprint THEN 'unchanged'
      ELSE 'changed'
    END,
    fingerprint = EXCLUDED.fingerprint,
    availability = 'present',
    last_seen_at = NOW(),
    removed_at = NULL,
    discovery_run_id = EXCLUDED.discovery_run_id,
    updated_at = NOW()
RETURNING id, tenant_id, project_id, connection_id, tool_name, title, description,
  input_schema, annotations, fingerprint, enabled, availability, drift_status,
  first_seen_at, last_seen_at, removed_at, discovery_run_id, created_at, updated_at
`

type UpsertMCPDiscoveredToolParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	ConnectionID   uuid.UUID       `json:"connection_id"`
	ToolName       string          `json:"tool_name"`
	Column5        interface{}     `json:"column_5"`
	Description    string          `json:"description"`
	InputSchema    json.RawMessage `json:"input_schema"`
	Annotations    json.RawMessage `json:"annotations"`
	Fingerprint    string          `json:"fingerprint"`
	DiscoveryRunID uuid.NullUUID   `json:"discovery_run_id"`
}

func (q *Queries) UpsertMCPDiscoveredTool(ctx context.Context, arg UpsertMCPDiscoveredToolParams) (McpDiscoveredTool, error) {
	row := q.db.QueryRowContext(ctx, upsertMCPDiscoveredTool,
		arg.TenantID,
		arg.ProjectID,
		arg.ConnectionID,
		arg.ToolName,
		arg.Column5,
		arg.Description,
		arg.InputSchema,
		arg.Annotations,
		arg.Fingerprint,
		arg.DiscoveryRunID,
	)
	var i McpDiscoveredTool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.ToolName,
		&i.Title,
		&i.Description,
		&i.InputSchema,
		&i.Annotations,
		&i.Fingerprint,
		&i.Enabled,
		&i.Availability,
		&i.DriftStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.RemovedAt,
		&i.DiscoveryRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
