// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_oauth_transaction.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeMCPAuthorizationTransaction = `-- name: ConsumeMCPAuthorizationTransaction :execrows
UPDATE mcp_oauth_transactions
SET status = 'consumed', updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3 AND status = 'pending'
`

type ConsumeMCPAuthorizationTransactionParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) ConsumeMCPAuthorizationTransaction(ctx context.Context, arg ConsumeMCPAuthorizationTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeMCPAuthorizationTransaction, arg.ID, arg.TenantID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createMCPAuthorizationTransaction = `-- name: CreateMCPAuthorizationTransaction :one
INSERT INTO mcp_oauth_transactions (tenant_id, project_id, connection_id, state_hash, verifier_reference, redirect_uri, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, project_id, connection_id, state_hash, verifier_reference,
  redirect_uri, expires_at, status, created_at, updated_at
`

type CreateMCPAuthorizationTransactionParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	ProjectID         uuid.UUID `json:"project_id"`
	ConnectionID      uuid.UUID `json:"connection_id"`
	StateHash         []byte    `json:"state_hash"`
	VerifierReference string    `json:"verifier_reference"`
	RedirectUri       string    `json:"redirect_uri"`
	ExpiresAt         time.Time `json:"expires_at"`
}

func (q *Queries) CreateMCPAuthorizationTransaction(ctx context.Context, arg CreateMCPAuthorizationTransactionParams) (McpOauthTransaction, error) {
	row := q.db.QueryRowContext(ctx, createMCPAuthorizationTransaction,
		arg.TenantID,
		arg.ProjectID,
		arg.ConnectionID,
		arg.StateHash,
		arg.VerifierReference,
		arg.RedirectUri,
		arg.ExpiresAt,
	)
	var i McpOauthTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.StateHash,
		&i.VerifierReference,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPendingMCPAuthorizationTransaction = `-- name: FindPendingMCPAuthorizationTransaction :one
SELECT id, tenant_id, project_id, connection_id, state_hash, verifier_reference,
  redirect_uri, expires_at, status, created_at, updated_at
FROM mcp_oauth_transactions
WHERE tenant_id = $1 AND project_id = $2 AND connection_id = $3
  AND state_hash = $4 AND status = 'pending' AND expires_at > NOW()
LIMIT 1
`

type FindPendingMCPAuthorizationTransactionParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	StateHash    []byte    `json:"state_hash"`
}

func (q *Queries) FindPendingMCPAuthorizationTransaction(ctx context.Context, arg FindPendingMCPAuthorizationTransactionParams) (McpOauthTransaction, error) {
	row := q.db.QueryRowContext(ctx, findPendingMCPAuthorizationTransaction,
		arg.TenantID,
		arg.ProjectID,
		arg.ConnectionID,
		arg.StateHash,
	)
	var i McpOauthTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.StateHash,
		&i.VerifierReference,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
