// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type UserRole string

const (
	UserRoleUSER  UserRole = "USER"
	UserRoleADMIN UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID            uuid.UUID             `json:"id"`
	TenantID      uuid.UUID             `json:"tenant_id"`
	Actor         string                `json:"actor"`
	Action        string                `json:"action"`
	ResourceType  string                `json:"resource_type"`
	ResourceID    string                `json:"resource_id"`
	Before        pqtype.NullRawMessage `json:"before"`
	After         pqtype.NullRawMessage `json:"after"`
	CorrelationID sql.NullString        `json:"correlation_id"`
	OccurredAt    time.Time             `json:"occurred_at"`
	CreatedAt     time.Time             `json:"created_at"`
}

type AuthApiKey struct {
	ID               uuid.UUID     `json:"id"`
	TenantID         uuid.UUID     `json:"tenant_id"`
	Name             string        `json:"name"`
	KeyPrefix        string        `json:"key_prefix"`
	KeyVerifier      []byte        `json:"key_verifier"`
	DefaultProjectID uuid.NullUUID `json:"default_project_id"`
	ExpiresAt        sql.NullTime  `json:"expires_at"`
	RevokedAt        sql.NullTime  `json:"revoked_at"`
	LastUsedAt       sql.NullTime  `json:"last_used_at"`
	CreatedBy        string        `json:"created_by"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type AuthApiKeyProject struct {
	ApiKeyID  uuid.UUID `json:"api_key_id"`
	ProjectID uuid.UUID `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
}

type AuthApiKeyScope struct {
	ApiKeyID  uuid.UUID `json:"api_key_id"`
	Scope     string    `json:"scope"`
	CreatedAt time.Time `json:"created_at"`
}

type AuthRoleBackfillRecord struct {
	ID               uuid.UUID `json:"id"`
	RoleAssignmentID uuid.UUID `json:"role_assignment_id"`
	InitialRole      string    `json:"initial_role"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type AuthSession struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Capability struct {
	ID                  uuid.UUID       `json:"id"`
	TenantID            uuid.UUID       `json:"tenant_id"`
	Name                string          `json:"name"`
	Description         sql.NullString  `json:"description"`
	ProviderType        string          `json:"provider_type"`
	ProviderID          sql.NullString  `json:"provider_id"`
	InputSchema         json.RawMessage `json:"input_schema"`
	OutputSchema        json.RawMessage `json:"output_schema"`
	Status              string          `json:"status"`
	Version             int32           `json:"version"`
	CredentialReference sql.NullString  `json:"credential_reference"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	ProviderTool        sql.NullString  `json:"provider_tool"`
}

type CapabilityBinding struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	CapabilityID uuid.UUID `json:"capability_id"`
	ScopeType    string    `json:"scope_type"`
	ScopeID      string    `json:"scope_id"`
	Permission   string    `json:"permission"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type CapabilityExecutionEvidence struct {
	ID                 uuid.UUID             `json:"id"`
	TenantID           uuid.UUID             `json:"tenant_id"`
	ProjectID          uuid.UUID             `json:"project_id"`
	WorkflowInstanceID uuid.UUID             `json:"workflow_instance_id"`
	StateID            string                `json:"state_id"`
	CapabilityID       uuid.UUID             `json:"capability_id"`
	CapabilityName     string                `json:"capability_name"`
	ProviderServer     string                `json:"provider_server"`
	ProviderTool       string                `json:"provider_tool"`
	CorrelationID      sql.NullString        `json:"correlation_id"`
	IdempotencyKey     string                `json:"idempotency_key"`
	Status             string                `json:"status"`
	Result             json.RawMessage       `json:"result"`
	Error              pqtype.NullRawMessage `json:"error"`
	CreatedAt          time.Time             `json:"created_at"`
	UpdatedAt          time.Time             `json:"updated_at"`
}

type ContextRecord struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	ScopeType string          `json:"scope_type"`
	ScopeID   string          `json:"scope_id"`
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	Version   int32           `json:"version"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Event struct {
	ID                 uuid.UUID       `json:"id"`
	TenantID           uuid.UUID       `json:"tenant_id"`
	EventID            string          `json:"event_id"`
	Type               string          `json:"type"`
	Source             string          `json:"source"`
	AggregateID        sql.NullString  `json:"aggregate_id"`
	WorkflowInstanceID uuid.NullUUID   `json:"workflow_instance_id"`
	Sequence           int64           `json:"sequence"`
	Timestamp          time.Time       `json:"timestamp"`
	Payload            json.RawMessage `json:"payload"`
	CorrelationID      sql.NullString  `json:"correlation_id"`
	CausationID        sql.NullString  `json:"causation_id"`
	IdempotencyKey     sql.NullString  `json:"idempotency_key"`
	CreatedAt          time.Time       `json:"created_at"`
}

type EventInbox struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	IdempotencyKey string          `json:"idempotency_key"`
	EventType      string          `json:"event_type"`
	Source         string          `json:"source"`
	Payload        json.RawMessage `json:"payload"`
	Status         string          `json:"status"`
	AttemptCount   int32           `json:"attempt_count"`
	ReceivedAt     time.Time       `json:"received_at"`
	ProcessedAt    sql.NullTime    `json:"processed_at"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type EventOutbox struct {
	ID           uuid.UUID       `json:"id"`
	TenantID     uuid.UUID       `json:"tenant_id"`
	EventID      uuid.NullUUID   `json:"event_id"`
	Payload      json.RawMessage `json:"payload"`
	Topic        string          `json:"topic"`
	Status       string          `json:"status"`
	AttemptCount int32           `json:"attempt_count"`
	PublishedAt  sql.NullTime    `json:"published_at"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type IdempotencyRecord struct {
	ID             uuid.UUID             `json:"id"`
	TenantID       uuid.UUID             `json:"tenant_id"`
	IdempotencyKey string                `json:"idempotency_key"`
	Scope          string                `json:"scope"`
	ResultStatus   string                `json:"result_status"`
	Payload        pqtype.NullRawMessage `json:"payload"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type Intent struct {
	ID          uuid.UUID       `json:"id"`
	TenantID    uuid.UUID       `json:"tenant_id"`
	ProjectID   uuid.UUID       `json:"project_id"`
	WorkflowID  uuid.UUID       `json:"workflow_id"`
	IntentKey   string          `json:"intent_key"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Examples    json.RawMessage `json:"examples"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type McpConnection struct {
	ID                  uuid.UUID       `json:"id"`
	TenantID            uuid.UUID       `json:"tenant_id"`
	ProjectID           uuid.UUID       `json:"project_id"`
	Name                string          `json:"name"`
	Alias               string          `json:"alias"`
	Transport           string          `json:"transport"`
	Endpoint            sql.NullString  `json:"endpoint"`
	StdioProfile        sql.NullString  `json:"stdio_profile"`
	StdioArgs           json.RawMessage `json:"stdio_args"`
	AuthType            string          `json:"auth_type"`
	CredentialReference sql.NullString  `json:"credential_reference"`
	CredentialStatus    string          `json:"credential_status"`
	Status              string          `json:"status"`
	LastTestStatus      string          `json:"last_test_status"`
	LastTestErrorCode   sql.NullString  `json:"last_test_error_code"`
	LastTestedAt        sql.NullTime    `json:"last_tested_at"`
	CreatedBy           string          `json:"created_by"`
	UpdatedBy           string          `json:"updated_by"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type McpDiscoveredTool struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	ConnectionID   uuid.UUID       `json:"connection_id"`
	ToolName       string          `json:"tool_name"`
	Title          sql.NullString  `json:"title"`
	Description    string          `json:"description"`
	InputSchema    json.RawMessage `json:"input_schema"`
	Annotations    json.RawMessage `json:"annotations"`
	Fingerprint    string          `json:"fingerprint"`
	Enabled        bool            `json:"enabled"`
	Availability   string          `json:"availability"`
	DriftStatus    string          `json:"drift_status"`
	FirstSeenAt    time.Time       `json:"first_seen_at"`
	LastSeenAt     time.Time       `json:"last_seen_at"`
	RemovedAt      sql.NullTime    `json:"removed_at"`
	DiscoveryRunID uuid.NullUUID   `json:"discovery_run_id"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type McpDiscoveryRun struct {
	ID                 uuid.UUID      `json:"id"`
	TenantID           uuid.UUID      `json:"tenant_id"`
	ProjectID          uuid.UUID      `json:"project_id"`
	ConnectionID       uuid.UUID      `json:"connection_id"`
	Status             string         `json:"status"`
	ToolCount          int32          `json:"tool_count"`
	CatalogFingerprint sql.NullString `json:"catalog_fingerprint"`
	ErrorCode          sql.NullString `json:"error_code"`
	StartedAt          time.Time      `json:"started_at"`
	CompletedAt        time.Time      `json:"completed_at"`
	CreatedBy          string         `json:"created_by"`
}

type MemoryReference struct {
	ID                       uuid.UUID       `json:"id"`
	TenantID                 uuid.UUID       `json:"tenant_id"`
	OwnerType                string          `json:"owner_type"`
	OwnerID                  string          `json:"owner_id"`
	Name                     string          `json:"name"`
	Value                    json.RawMessage `json:"value"`
	SourceWorkflowInstanceID uuid.NullUUID   `json:"source_workflow_instance_id"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
}

type Policy struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	ScopeType string          `json:"scope_type"`
	ScopeID   string          `json:"scope_id"`
	Type      string          `json:"type"`
	Content   json.RawMessage `json:"content"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Project struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProjectCapabilityMcpBinding struct {
	ID                   uuid.UUID `json:"id"`
	TenantID             uuid.UUID `json:"tenant_id"`
	ProjectID            uuid.UUID `json:"project_id"`
	CapabilityID         uuid.UUID `json:"capability_id"`
	McpConnectionID      uuid.UUID `json:"mcp_connection_id"`
	McpDiscoveredToolID  uuid.UUID `json:"mcp_discovered_tool_id"`
	BoundToolFingerprint string    `json:"bound_tool_fingerprint"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type RoleAssignment struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RuntimeTraceEntry struct {
	ID                 uuid.UUID       `json:"id"`
	TenantID           uuid.UUID       `json:"tenant_id"`
	WorkflowInstanceID uuid.UUID       `json:"workflow_instance_id"`
	TurnID             sql.NullString  `json:"turn_id"`
	Sequence           int64           `json:"sequence"`
	Stage              string          `json:"stage"`
	Source             string          `json:"source"`
	Status             string          `json:"status"`
	OccurredAt         time.Time       `json:"occurred_at"`
	CorrelationID      sql.NullString  `json:"correlation_id"`
	DurationMs         sql.NullInt64   `json:"duration_ms"`
	ReasonCode         sql.NullString  `json:"reason_code"`
	ErrorCode          sql.NullString  `json:"error_code"`
	ProviderAlias      sql.NullString  `json:"provider_alias"`
	ProviderReference  sql.NullString  `json:"provider_reference"`
	Summary            sql.NullString  `json:"summary"`
	Attributes         json.RawMessage `json:"attributes"`
}

type State struct {
	ID                uuid.UUID       `json:"id"`
	WorkflowVersionID uuid.UUID       `json:"workflow_version_id"`
	Key               string          `json:"key"`
	Kind              string          `json:"kind"`
	Name              string          `json:"name"`
	Description       sql.NullString  `json:"description"`
	Instructions      sql.NullString  `json:"instructions"`
	RequiredContext   json.RawMessage `json:"required_context"`
	Capabilities      json.RawMessage `json:"capabilities"`
	Policy            json.RawMessage `json:"policy"`
	IsTerminal        bool            `json:"is_terminal"`
	Position          json.RawMessage `json:"position"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type StateInstance struct {
	ID                 uuid.UUID     `json:"id"`
	TenantID           uuid.UUID     `json:"tenant_id"`
	WorkflowInstanceID uuid.UUID     `json:"workflow_instance_id"`
	WorkflowVersionID  uuid.UUID     `json:"workflow_version_id"`
	StateKey           string        `json:"state_key"`
	StateID            uuid.NullUUID `json:"state_id"`
	Status             string        `json:"status"`
	Version            int32         `json:"version"`
	RetryCount         int32         `json:"retry_count"`
	EnteredAt          time.Time     `json:"entered_at"`
	ExpiresAt          sql.NullTime  `json:"expires_at"`
	ExitedAt           sql.NullTime  `json:"exited_at"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
}

type Tenant struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Transition struct {
	ID                uuid.UUID `json:"id"`
	WorkflowVersionID uuid.UUID `json:"workflow_version_id"`
	Key               string    `json:"key"`
	SourceStateID     uuid.UUID `json:"source_state_id"`
	TargetStateID     uuid.UUID `json:"target_state_id"`
	Event             string    `json:"event"`
	Priority          int32     `json:"priority"`
	IsActive          bool      `json:"is_active"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type TransitionGuard struct {
	ID                uuid.UUID       `json:"id"`
	TransitionID      uuid.UUID       `json:"transition_id"`
	WorkflowVersionID uuid.UUID       `json:"workflow_version_id"`
	Logic             string          `json:"logic"`
	Conditions        json.RawMessage `json:"conditions"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         string         `json:"name"`
	Role         UserRole       `json:"role"`
	Status       UserStatus     `json:"status"`
	Photo        sql.NullString `json:"photo"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type UserIdentity struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Provider        string    `json:"provider"`
	SubjectID       string    `json:"subject_id"`
	AutoProvisioned bool      `json:"auto_provisioned"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Workflow struct {
	ID              uuid.UUID       `json:"id"`
	TenantID        uuid.UUID       `json:"tenant_id"`
	ProjectID       uuid.UUID       `json:"project_id"`
	Slug            string          `json:"slug"`
	Name            string          `json:"name"`
	Description     sql.NullString  `json:"description"`
	Status          string          `json:"status"`
	CurrentVersion  int32           `json:"current_version"`
	Version         int32           `json:"version"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	DraftDefinition json.RawMessage `json:"draft_definition"`
}

type WorkflowInstance struct {
	ID                     uuid.UUID      `json:"id"`
	TenantID               uuid.UUID      `json:"tenant_id"`
	WorkflowID             uuid.UUID      `json:"workflow_id"`
	WorkflowVersionID      uuid.UUID      `json:"workflow_version_id"`
	CorrelationKey         sql.NullString `json:"correlation_key"`
	Status                 string         `json:"status"`
	Version                int32          `json:"version"`
	CurrentStateInstanceID uuid.NullUUID  `json:"current_state_instance_id"`
	StartedAt              sql.NullTime   `json:"started_at"`
	CompletedAt            sql.NullTime   `json:"completed_at"`
	ExpiresAt              sql.NullTime   `json:"expires_at"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type WorkflowVersion struct {
	ID         uuid.UUID       `json:"id"`
	WorkflowID uuid.UUID       `json:"workflow_id"`
	TenantID   uuid.UUID       `json:"tenant_id"`
	ProjectID  uuid.UUID       `json:"project_id"`
	VersionNo  int32           `json:"version_no"`
	Definition json.RawMessage `json:"definition"`
	Status     string          `json:"status"`
	IsCurrent  bool            `json:"is_current"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}
