// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_capability_mcp_binding.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteProjectCapabilityMCPBinding = `-- name: DeleteProjectCapabilityMCPBinding :exec
DELETE FROM project_capability_mcp_bindings
WHERE tenant_id = $1
  AND project_id = $2
  AND capability_id = $3
`

type DeleteProjectCapabilityMCPBindingParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	CapabilityID uuid.UUID `json:"capability_id"`
}

func (q *Queries) DeleteProjectCapabilityMCPBinding(ctx context.Context, arg DeleteProjectCapabilityMCPBindingParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectCapabilityMCPBinding, arg.TenantID, arg.ProjectID, arg.CapabilityID)
	return err
}

const findProjectCapabilityMCPBinding = `-- name: FindProjectCapabilityMCPBinding :one
SELECT
  binding.id,
  binding.tenant_id,
  binding.project_id,
  binding.capability_id,
  cap.name AS capability_name,
  cap.description AS capability_description,
  binding.mcp_connection_id AS connection_id,
  conn.name AS connection_name,
  conn.alias AS connection_alias,
  conn.status AS connection_status,
  binding.mcp_discovered_tool_id AS tool_id,
  tool.tool_name,
  tool.title AS tool_title,
  tool.description AS tool_description,
  binding.bound_tool_fingerprint,
  tool.fingerprint AS current_tool_fingerprint,
  tool.enabled AS tool_enabled,
  tool.availability AS tool_availability,
  tool.drift_status AS tool_drift_status,
  CASE
    WHEN conn.status <> 'enabled' THEN 'CONNECTION_DISABLED'
    WHEN tool.enabled = FALSE THEN 'TOOL_DISABLED'
    WHEN tool.availability <> 'present' THEN 'TOOL_REMOVED'
    WHEN binding.bound_tool_fingerprint <> tool.fingerprint THEN 'STALE'
    ELSE 'ACTIVE'
  END AS health,
  CASE
    WHEN conn.status <> 'enabled' THEN 'Provider connection is disabled'
    WHEN tool.enabled = FALSE THEN 'Provider tool is disabled'
    WHEN tool.availability <> 'present' THEN 'Provider tool was removed from the latest catalog'
    WHEN binding.bound_tool_fingerprint <> tool.fingerprint THEN 'Provider tool catalog changed; rebind required'
    ELSE ''
  END AS health_reason,
  binding.created_at,
  binding.updated_at
FROM project_capability_mcp_bindings binding
JOIN capabilities cap
  ON cap.tenant_id = binding.tenant_id
 AND cap.id = binding.capability_id
JOIN mcp_connections conn
  ON conn.tenant_id = binding.tenant_id
 AND conn.project_id = binding.project_id
 AND conn.id = binding.mcp_connection_id
JOIN mcp_discovered_tools tool
  ON tool.tenant_id = binding.tenant_id
 AND tool.project_id = binding.project_id
 AND tool.connection_id = binding.mcp_connection_id
 AND tool.id = binding.mcp_discovered_tool_id
WHERE binding.tenant_id = $1
  AND binding.project_id = $2
  AND binding.capability_id = $3
LIMIT 1
`

type FindProjectCapabilityMCPBindingParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	CapabilityID uuid.UUID `json:"capability_id"`
}

type FindProjectCapabilityMCPBindingRow struct {
	ID                     uuid.UUID      `json:"id"`
	TenantID               uuid.UUID      `json:"tenant_id"`
	ProjectID              uuid.UUID      `json:"project_id"`
	CapabilityID           uuid.UUID      `json:"capability_id"`
	CapabilityName         string         `json:"capability_name"`
	CapabilityDescription  sql.NullString `json:"capability_description"`
	ConnectionID           uuid.UUID      `json:"connection_id"`
	ConnectionName         string         `json:"connection_name"`
	ConnectionAlias        string         `json:"connection_alias"`
	ConnectionStatus       string         `json:"connection_status"`
	ToolID                 uuid.UUID      `json:"tool_id"`
	ToolName               string         `json:"tool_name"`
	ToolTitle              sql.NullString `json:"tool_title"`
	ToolDescription        string         `json:"tool_description"`
	BoundToolFingerprint   string         `json:"bound_tool_fingerprint"`
	CurrentToolFingerprint string         `json:"current_tool_fingerprint"`
	ToolEnabled            bool           `json:"tool_enabled"`
	ToolAvailability       string         `json:"tool_availability"`
	ToolDriftStatus        string         `json:"tool_drift_status"`
	Health                 string         `json:"health"`
	HealthReason           string         `json:"health_reason"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

func (q *Queries) FindProjectCapabilityMCPBinding(ctx context.Context, arg FindProjectCapabilityMCPBindingParams) (FindProjectCapabilityMCPBindingRow, error) {
	row := q.db.QueryRowContext(ctx, findProjectCapabilityMCPBinding, arg.TenantID, arg.ProjectID, arg.CapabilityID)
	var i FindProjectCapabilityMCPBindingRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.CapabilityID,
		&i.CapabilityName,
		&i.CapabilityDescription,
		&i.ConnectionID,
		&i.ConnectionName,
		&i.ConnectionAlias,
		&i.ConnectionStatus,
		&i.ToolID,
		&i.ToolName,
		&i.ToolTitle,
		&i.ToolDescription,
		&i.BoundToolFingerprint,
		&i.CurrentToolFingerprint,
		&i.ToolEnabled,
		&i.ToolAvailability,
		&i.ToolDriftStatus,
		&i.Health,
		&i.HealthReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEligibleMCPToolOptions = `-- name: ListEligibleMCPToolOptions :many
SELECT
  conn.id AS connection_id,
  conn.name AS connection_name,
  conn.alias AS connection_alias,
  conn.status AS connection_status,
  tool.id AS tool_id,
  tool.tool_name AS tool_name,
  tool.title AS tool_title,
  tool.description AS tool_description,
  tool.input_schema AS tool_input_schema,
  tool.fingerprint AS tool_fingerprint
FROM mcp_connections conn
JOIN mcp_discovered_tools tool
  ON tool.tenant_id = conn.tenant_id
 AND tool.project_id = conn.project_id
 AND tool.connection_id = conn.id
WHERE conn.tenant_id = $1
  AND conn.project_id = $2
  AND conn.status = 'enabled'
  AND tool.enabled = TRUE
  AND tool.availability = 'present'
ORDER BY conn.alias ASC, tool.tool_name ASC
`

type ListEligibleMCPToolOptionsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type ListEligibleMCPToolOptionsRow struct {
	ConnectionID     uuid.UUID       `json:"connection_id"`
	ConnectionName   string          `json:"connection_name"`
	ConnectionAlias  string          `json:"connection_alias"`
	ConnectionStatus string          `json:"connection_status"`
	ToolID           uuid.UUID       `json:"tool_id"`
	ToolName         string          `json:"tool_name"`
	ToolTitle        sql.NullString  `json:"tool_title"`
	ToolDescription  string          `json:"tool_description"`
	ToolInputSchema  json.RawMessage `json:"tool_input_schema"`
	ToolFingerprint  string          `json:"tool_fingerprint"`
}

func (q *Queries) ListEligibleMCPToolOptions(ctx context.Context, arg ListEligibleMCPToolOptionsParams) ([]ListEligibleMCPToolOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEligibleMCPToolOptions, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleMCPToolOptionsRow
	for rows.Next() {
		var i ListEligibleMCPToolOptionsRow
		if err := rows.Scan(
			&i.ConnectionID,
			&i.ConnectionName,
			&i.ConnectionAlias,
			&i.ConnectionStatus,
			&i.ToolID,
			&i.ToolName,
			&i.ToolTitle,
			&i.ToolDescription,
			&i.ToolInputSchema,
			&i.ToolFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectCapabilityMCPBindings = `-- name: ListProjectCapabilityMCPBindings :many
SELECT
  binding.id,
  binding.tenant_id,
  binding.project_id,
  binding.capability_id,
  cap.name AS capability_name,
  cap.description AS capability_description,
  binding.mcp_connection_id AS connection_id,
  conn.name AS connection_name,
  conn.alias AS connection_alias,
  conn.status AS connection_status,
  binding.mcp_discovered_tool_id AS tool_id,
  tool.tool_name,
  tool.title AS tool_title,
  tool.description AS tool_description,
  binding.bound_tool_fingerprint,
  tool.fingerprint AS current_tool_fingerprint,
  tool.enabled AS tool_enabled,
  tool.availability AS tool_availability,
  tool.drift_status AS tool_drift_status,
  CASE
    WHEN conn.status <> 'enabled' THEN 'CONNECTION_DISABLED'
    WHEN tool.enabled = FALSE THEN 'TOOL_DISABLED'
    WHEN tool.availability <> 'present' THEN 'TOOL_REMOVED'
    WHEN binding.bound_tool_fingerprint <> tool.fingerprint THEN 'STALE'
    ELSE 'ACTIVE'
  END AS health,
  CASE
    WHEN conn.status <> 'enabled' THEN 'Provider connection is disabled'
    WHEN tool.enabled = FALSE THEN 'Provider tool is disabled'
    WHEN tool.availability <> 'present' THEN 'Provider tool was removed from the latest catalog'
    WHEN binding.bound_tool_fingerprint <> tool.fingerprint THEN 'Provider tool catalog changed; rebind required'
    ELSE ''
  END AS health_reason,
  binding.created_at,
  binding.updated_at
FROM project_capability_mcp_bindings binding
JOIN capabilities cap
  ON cap.tenant_id = binding.tenant_id
 AND cap.id = binding.capability_id
JOIN mcp_connections conn
  ON conn.tenant_id = binding.tenant_id
 AND conn.project_id = binding.project_id
 AND conn.id = binding.mcp_connection_id
JOIN mcp_discovered_tools tool
  ON tool.tenant_id = binding.tenant_id
 AND tool.project_id = binding.project_id
 AND tool.connection_id = binding.mcp_connection_id
 AND tool.id = binding.mcp_discovered_tool_id
WHERE binding.tenant_id = $1
  AND binding.project_id = $2
ORDER BY cap.name ASC
`

type ListProjectCapabilityMCPBindingsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type ListProjectCapabilityMCPBindingsRow struct {
	ID                     uuid.UUID      `json:"id"`
	TenantID               uuid.UUID      `json:"tenant_id"`
	ProjectID              uuid.UUID      `json:"project_id"`
	CapabilityID           uuid.UUID      `json:"capability_id"`
	CapabilityName         string         `json:"capability_name"`
	CapabilityDescription  sql.NullString `json:"capability_description"`
	ConnectionID           uuid.UUID      `json:"connection_id"`
	ConnectionName         string         `json:"connection_name"`
	ConnectionAlias        string         `json:"connection_alias"`
	ConnectionStatus       string         `json:"connection_status"`
	ToolID                 uuid.UUID      `json:"tool_id"`
	ToolName               string         `json:"tool_name"`
	ToolTitle              sql.NullString `json:"tool_title"`
	ToolDescription        string         `json:"tool_description"`
	BoundToolFingerprint   string         `json:"bound_tool_fingerprint"`
	CurrentToolFingerprint string         `json:"current_tool_fingerprint"`
	ToolEnabled            bool           `json:"tool_enabled"`
	ToolAvailability       string         `json:"tool_availability"`
	ToolDriftStatus        string         `json:"tool_drift_status"`
	Health                 string         `json:"health"`
	HealthReason           string         `json:"health_reason"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

func (q *Queries) ListProjectCapabilityMCPBindings(ctx context.Context, arg ListProjectCapabilityMCPBindingsParams) ([]ListProjectCapabilityMCPBindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectCapabilityMCPBindings, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectCapabilityMCPBindingsRow
	for rows.Next() {
		var i ListProjectCapabilityMCPBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.CapabilityID,
			&i.CapabilityName,
			&i.CapabilityDescription,
			&i.ConnectionID,
			&i.ConnectionName,
			&i.ConnectionAlias,
			&i.ConnectionStatus,
			&i.ToolID,
			&i.ToolName,
			&i.ToolTitle,
			&i.ToolDescription,
			&i.BoundToolFingerprint,
			&i.CurrentToolFingerprint,
			&i.ToolEnabled,
			&i.ToolAvailability,
			&i.ToolDriftStatus,
			&i.Health,
			&i.HealthReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectCapabilityMCPBinding = `-- name: UpsertProjectCapabilityMCPBinding :exec
INSERT INTO project_capability_mcp_bindings (
  tenant_id, project_id, capability_id, mcp_connection_id,
  mcp_discovered_tool_id, bound_tool_fingerprint
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (project_id, capability_id) DO UPDATE
SET mcp_connection_id = EXCLUDED.mcp_connection_id,
    mcp_discovered_tool_id = EXCLUDED.mcp_discovered_tool_id,
    bound_tool_fingerprint = EXCLUDED.bound_tool_fingerprint,
    updated_at = NOW()
`

type UpsertProjectCapabilityMCPBindingParams struct {
	TenantID             uuid.UUID `json:"tenant_id"`
	ProjectID            uuid.UUID `json:"project_id"`
	CapabilityID         uuid.UUID `json:"capability_id"`
	McpConnectionID      uuid.UUID `json:"mcp_connection_id"`
	McpDiscoveredToolID  uuid.UUID `json:"mcp_discovered_tool_id"`
	BoundToolFingerprint string    `json:"bound_tool_fingerprint"`
}

func (q *Queries) UpsertProjectCapabilityMCPBinding(ctx context.Context, arg UpsertProjectCapabilityMCPBindingParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectCapabilityMCPBinding,
		arg.TenantID,
		arg.ProjectID,
		arg.CapabilityID,
		arg.McpConnectionID,
		arg.McpDiscoveredToolID,
		arg.BoundToolFingerprint,
	)
	return err
}
