// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignRole = `-- name: AssignRole :one

INSERT INTO role_assignments (user_id, tenant_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, tenant_id) DO UPDATE SET role = EXCLUDED.role, updated_at = NOW()
RETURNING id, user_id, tenant_id, role, created_at, updated_at
`

type AssignRoleParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Role     string    `json:"role"`
}

// Tenant-scoped RBAC queries (PRD 80, 81). Every query takes an explicit
// tenant_id (PRD 4, 96) and filters by it so cross-tenant access is impossible
// at the data-access layer.
func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) (RoleAssignment, error) {
	row := q.db.QueryRowContext(ctx, assignRole, arg.UserID, arg.TenantID, arg.Role)
	var i RoleAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRoleByUserAndTenant = `-- name: FindRoleByUserAndTenant :one
SELECT id, user_id, tenant_id, role, created_at, updated_at
FROM role_assignments
WHERE user_id = $1 AND tenant_id = $2
LIMIT 1
`

type FindRoleByUserAndTenantParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindRoleByUserAndTenant(ctx context.Context, arg FindRoleByUserAndTenantParams) (RoleAssignment, error) {
	row := q.db.QueryRowContext(ctx, findRoleByUserAndTenant, arg.UserID, arg.TenantID)
	var i RoleAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, user_id, tenant_id, role, created_at, updated_at
FROM role_assignments
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRolesByTenant(ctx context.Context, tenantID uuid.UUID) ([]RoleAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignment
	for rows.Next() {
		var i RoleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleAssignment = `-- name: RemoveRoleAssignment :exec
DELETE FROM role_assignments
WHERE user_id = $1 AND tenant_id = $2
`

type RemoveRoleAssignmentParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RemoveRoleAssignment(ctx context.Context, arg RemoveRoleAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleAssignment, arg.UserID, arg.TenantID)
	return err
}
