// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appendRuntimeTraceEntry = `-- name: AppendRuntimeTraceEntry :one
INSERT INTO runtime_trace_entries (
  tenant_id, workflow_instance_id, turn_id, stage, source, status, occurred_at,
  correlation_id, duration_ms, reason_code, error_code, provider_alias,
  provider_reference, summary, attributes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, tenant_id, workflow_instance_id, turn_id, sequence, stage, source, status,
          occurred_at, correlation_id, duration_ms, reason_code, error_code,
          provider_alias, provider_reference, summary, attributes
`

type AppendRuntimeTraceEntryParams struct {
	TenantID           uuid.UUID       `json:"tenant_id"`
	WorkflowInstanceID uuid.UUID       `json:"workflow_instance_id"`
	TurnID             sql.NullString  `json:"turn_id"`
	Stage              string          `json:"stage"`
	Source             string          `json:"source"`
	Status             string          `json:"status"`
	OccurredAt         time.Time       `json:"occurred_at"`
	CorrelationID      sql.NullString  `json:"correlation_id"`
	DurationMs         sql.NullInt64   `json:"duration_ms"`
	ReasonCode         sql.NullString  `json:"reason_code"`
	ErrorCode          sql.NullString  `json:"error_code"`
	ProviderAlias      sql.NullString  `json:"provider_alias"`
	ProviderReference  sql.NullString  `json:"provider_reference"`
	Summary            sql.NullString  `json:"summary"`
	Attributes         json.RawMessage `json:"attributes"`
}

func (q *Queries) AppendRuntimeTraceEntry(ctx context.Context, arg AppendRuntimeTraceEntryParams) (RuntimeTraceEntry, error) {
	row := q.db.QueryRowContext(ctx, appendRuntimeTraceEntry,
		arg.TenantID,
		arg.WorkflowInstanceID,
		arg.TurnID,
		arg.Stage,
		arg.Source,
		arg.Status,
		arg.OccurredAt,
		arg.CorrelationID,
		arg.DurationMs,
		arg.ReasonCode,
		arg.ErrorCode,
		arg.ProviderAlias,
		arg.ProviderReference,
		arg.Summary,
		arg.Attributes,
	)
	var i RuntimeTraceEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowInstanceID,
		&i.TurnID,
		&i.Sequence,
		&i.Stage,
		&i.Source,
		&i.Status,
		&i.OccurredAt,
		&i.CorrelationID,
		&i.DurationMs,
		&i.ReasonCode,
		&i.ErrorCode,
		&i.ProviderAlias,
		&i.ProviderReference,
		&i.Summary,
		&i.Attributes,
	)
	return i, err
}

const findRuntimeWorkflow = `-- name: FindRuntimeWorkflow :one

SELECT id, tenant_id, project_id, slug, name, description, status, current_version, version, created_at, updated_at, draft_definition
FROM workflows
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type FindRuntimeWorkflowParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Runtime Inspector read projections. Every query is tenant-scoped.
func (q *Queries) FindRuntimeWorkflow(ctx context.Context, arg FindRuntimeWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, findRuntimeWorkflow, arg.ID, arg.TenantID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftDefinition,
	)
	return i, err
}

const findRuntimeWorkflowVersion = `-- name: FindRuntimeWorkflowVersion :one
SELECT id, workflow_id, tenant_id, project_id, version_no, definition, status, is_current, created_at, updated_at
FROM workflow_versions
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type FindRuntimeWorkflowVersionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindRuntimeWorkflowVersion(ctx context.Context, arg FindRuntimeWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRowContext(ctx, findRuntimeWorkflowVersion, arg.ID, arg.TenantID)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TenantID,
		&i.ProjectID,
		&i.VersionNo,
		&i.Definition,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRuntimeStatesByVersion = `-- name: ListRuntimeStatesByVersion :many
SELECT s.id, s.workflow_version_id, s.key, s.kind, s.name, s.description, s.instructions,
       s.required_context, s.capabilities, s.policy, s.is_terminal, s.position, s.created_at, s.updated_at
FROM states s
JOIN workflow_versions wv ON wv.id = s.workflow_version_id
WHERE s.workflow_version_id = $1 AND wv.tenant_id = $2
ORDER BY s.created_at ASC, s.id ASC
`

type ListRuntimeStatesByVersionParams struct {
	WorkflowVersionID uuid.UUID `json:"workflow_version_id"`
	TenantID          uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListRuntimeStatesByVersion(ctx context.Context, arg ListRuntimeStatesByVersionParams) ([]State, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeStatesByVersion, arg.WorkflowVersionID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []State
	for rows.Next() {
		var i State
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.Key,
			&i.Kind,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.RequiredContext,
			&i.Capabilities,
			&i.Policy,
			&i.IsTerminal,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeTraceByInstance = `-- name: ListRuntimeTraceByInstance :many
SELECT id, tenant_id, workflow_instance_id, turn_id, sequence, stage, source, status,
       occurred_at, correlation_id, duration_ms, reason_code, error_code,
       provider_alias, provider_reference, summary, attributes
FROM runtime_trace_entries
WHERE tenant_id = $1 AND workflow_instance_id = $2
ORDER BY sequence ASC, occurred_at ASC, id ASC
`

type ListRuntimeTraceByInstanceParams struct {
	TenantID           uuid.UUID `json:"tenant_id"`
	WorkflowInstanceID uuid.UUID `json:"workflow_instance_id"`
}

func (q *Queries) ListRuntimeTraceByInstance(ctx context.Context, arg ListRuntimeTraceByInstanceParams) ([]RuntimeTraceEntry, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeTraceByInstance, arg.TenantID, arg.WorkflowInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuntimeTraceEntry
	for rows.Next() {
		var i RuntimeTraceEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowInstanceID,
			&i.TurnID,
			&i.Sequence,
			&i.Stage,
			&i.Source,
			&i.Status,
			&i.OccurredAt,
			&i.CorrelationID,
			&i.DurationMs,
			&i.ReasonCode,
			&i.ErrorCode,
			&i.ProviderAlias,
			&i.ProviderReference,
			&i.Summary,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeTraceByTurn = `-- name: ListRuntimeTraceByTurn :many
SELECT id, tenant_id, workflow_instance_id, turn_id, sequence, stage, source, status,
       occurred_at, correlation_id, duration_ms, reason_code, error_code,
       provider_alias, provider_reference, summary, attributes
FROM runtime_trace_entries
WHERE tenant_id = $1 AND workflow_instance_id = $2 AND turn_id = $3
ORDER BY sequence ASC, occurred_at ASC, id ASC
`

type ListRuntimeTraceByTurnParams struct {
	TenantID           uuid.UUID      `json:"tenant_id"`
	WorkflowInstanceID uuid.UUID      `json:"workflow_instance_id"`
	TurnID             sql.NullString `json:"turn_id"`
}

func (q *Queries) ListRuntimeTraceByTurn(ctx context.Context, arg ListRuntimeTraceByTurnParams) ([]RuntimeTraceEntry, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeTraceByTurn, arg.TenantID, arg.WorkflowInstanceID, arg.TurnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuntimeTraceEntry
	for rows.Next() {
		var i RuntimeTraceEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowInstanceID,
			&i.TurnID,
			&i.Sequence,
			&i.Stage,
			&i.Source,
			&i.Status,
			&i.OccurredAt,
			&i.CorrelationID,
			&i.DurationMs,
			&i.ReasonCode,
			&i.ErrorCode,
			&i.ProviderAlias,
			&i.ProviderReference,
			&i.Summary,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStateInstancesByWorkflowInstance = `-- name: ListStateInstancesByWorkflowInstance :many
SELECT id, tenant_id, workflow_instance_id, workflow_version_id, state_key, state_id, status,
       version, retry_count, entered_at, expires_at, exited_at, created_at, updated_at
FROM state_instances
WHERE workflow_instance_id = $1 AND tenant_id = $2
ORDER BY entered_at ASC, created_at ASC, id ASC
`

type ListStateInstancesByWorkflowInstanceParams struct {
	WorkflowInstanceID uuid.UUID `json:"workflow_instance_id"`
	TenantID           uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListStateInstancesByWorkflowInstance(ctx context.Context, arg ListStateInstancesByWorkflowInstanceParams) ([]StateInstance, error) {
	rows, err := q.db.QueryContext(ctx, listStateInstancesByWorkflowInstance, arg.WorkflowInstanceID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StateInstance
	for rows.Next() {
		var i StateInstance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowInstanceID,
			&i.WorkflowVersionID,
			&i.StateKey,
			&i.StateID,
			&i.Status,
			&i.Version,
			&i.RetryCount,
			&i.EnteredAt,
			&i.ExpiresAt,
			&i.ExitedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
