// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, name, slug, status)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, slug, status, created_at, updated_at
`

type CreateProjectParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.TenantID,
		arg.Name,
		arg.Slug,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createState = `-- name: CreateState :one
INSERT INTO states (workflow_version_id, key, kind, name, description, instructions, required_context, capabilities, policy, is_terminal, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workflow_version_id, key, kind, name, description, instructions, required_context, capabilities, policy, is_terminal, position, created_at, updated_at
`

type CreateStateParams struct {
	WorkflowVersionID uuid.UUID       `json:"workflow_version_id"`
	Key               string          `json:"key"`
	Kind              string          `json:"kind"`
	Name              string          `json:"name"`
	Description       sql.NullString  `json:"description"`
	Instructions      sql.NullString  `json:"instructions"`
	RequiredContext   json.RawMessage `json:"required_context"`
	Capabilities      json.RawMessage `json:"capabilities"`
	Policy            json.RawMessage `json:"policy"`
	IsTerminal        bool            `json:"is_terminal"`
	Position          json.RawMessage `json:"position"`
}

func (q *Queries) CreateState(ctx context.Context, arg CreateStateParams) (State, error) {
	row := q.db.QueryRowContext(ctx, createState,
		arg.WorkflowVersionID,
		arg.Key,
		arg.Kind,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.RequiredContext,
		arg.Capabilities,
		arg.Policy,
		arg.IsTerminal,
		arg.Position,
	)
	var i State
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.Key,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.RequiredContext,
		&i.Capabilities,
		&i.Policy,
		&i.IsTerminal,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransition = `-- name: CreateTransition :one
INSERT INTO transitions (workflow_version_id, key, source_state_id, target_state_id, event, priority, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workflow_version_id, key, source_state_id, target_state_id, event, priority, is_active, created_at, updated_at
`

type CreateTransitionParams struct {
	WorkflowVersionID uuid.UUID `json:"workflow_version_id"`
	Key               string    `json:"key"`
	SourceStateID     uuid.UUID `json:"source_state_id"`
	TargetStateID     uuid.UUID `json:"target_state_id"`
	Event             string    `json:"event"`
	Priority          int32     `json:"priority"`
	IsActive          bool      `json:"is_active"`
}

func (q *Queries) CreateTransition(ctx context.Context, arg CreateTransitionParams) (Transition, error) {
	row := q.db.QueryRowContext(ctx, createTransition,
		arg.WorkflowVersionID,
		arg.Key,
		arg.SourceStateID,
		arg.TargetStateID,
		arg.Event,
		arg.Priority,
		arg.IsActive,
	)
	var i Transition
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.Key,
		&i.SourceStateID,
		&i.TargetStateID,
		&i.Event,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransitionGuard = `-- name: CreateTransitionGuard :one
INSERT INTO transition_guards (transition_id, workflow_version_id, logic, conditions)
VALUES ($1, $2, $3, $4)
RETURNING id, transition_id, workflow_version_id, logic, conditions, created_at, updated_at
`

type CreateTransitionGuardParams struct {
	TransitionID      uuid.UUID       `json:"transition_id"`
	WorkflowVersionID uuid.UUID       `json:"workflow_version_id"`
	Logic             string          `json:"logic"`
	Conditions        json.RawMessage `json:"conditions"`
}

func (q *Queries) CreateTransitionGuard(ctx context.Context, arg CreateTransitionGuardParams) (TransitionGuard, error) {
	row := q.db.QueryRowContext(ctx, createTransitionGuard,
		arg.TransitionID,
		arg.WorkflowVersionID,
		arg.Logic,
		arg.Conditions,
	)
	var i TransitionGuard
	err := row.Scan(
		&i.ID,
		&i.TransitionID,
		&i.WorkflowVersionID,
		&i.Logic,
		&i.Conditions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (tenant_id, project_id, slug, name, description, status, draft_definition)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, project_id, slug, name, description, status, current_version, version, created_at, updated_at, draft_definition
`

type CreateWorkflowParams struct {
	TenantID        uuid.UUID       `json:"tenant_id"`
	ProjectID       uuid.UUID       `json:"project_id"`
	Slug            string          `json:"slug"`
	Name            string          `json:"name"`
	Description     sql.NullString  `json:"description"`
	Status          string          `json:"status"`
	DraftDefinition json.RawMessage `json:"draft_definition"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow,
		arg.TenantID,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.DraftDefinition,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftDefinition,
	)
	return i, err
}

const createWorkflowVersion = `-- name: CreateWorkflowVersion :one
INSERT INTO workflow_versions (workflow_id, tenant_id, project_id, version_no, definition, status, is_current)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workflow_id, tenant_id, project_id, version_no, definition, status, is_current, created_at, updated_at
`

type CreateWorkflowVersionParams struct {
	WorkflowID uuid.UUID       `json:"workflow_id"`
	TenantID   uuid.UUID       `json:"tenant_id"`
	ProjectID  uuid.UUID       `json:"project_id"`
	VersionNo  int32           `json:"version_no"`
	Definition json.RawMessage `json:"definition"`
	Status     string          `json:"status"`
	IsCurrent  bool            `json:"is_current"`
}

func (q *Queries) CreateWorkflowVersion(ctx context.Context, arg CreateWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowVersion,
		arg.WorkflowID,
		arg.TenantID,
		arg.ProjectID,
		arg.VersionNo,
		arg.Definition,
		arg.Status,
		arg.IsCurrent,
	)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TenantID,
		&i.ProjectID,
		&i.VersionNo,
		&i.Definition,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCurrentWorkflowVersion = `-- name: FindCurrentWorkflowVersion :one
SELECT id, workflow_id, tenant_id, project_id, version_no, definition, status, is_current, created_at, updated_at
FROM workflow_versions
WHERE workflow_id = $1 AND tenant_id = $2 AND project_id = $3 AND is_current = TRUE
LIMIT 1
`

type FindCurrentWorkflowVersionParams struct {
	WorkflowID uuid.UUID `json:"workflow_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	ProjectID  uuid.UUID `json:"project_id"`
}

func (q *Queries) FindCurrentWorkflowVersion(ctx context.Context, arg FindCurrentWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRowContext(ctx, findCurrentWorkflowVersion, arg.WorkflowID, arg.TenantID, arg.ProjectID)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TenantID,
		&i.ProjectID,
		&i.VersionNo,
		&i.Definition,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCurrentWorkflowVersionByWorkflow = `-- name: FindCurrentWorkflowVersionByWorkflow :one
SELECT id, workflow_id, tenant_id, project_id, version_no, definition, status, is_current, created_at, updated_at
FROM workflow_versions
WHERE workflow_id = $1 AND tenant_id = $2 AND is_current = TRUE
LIMIT 1
`

type FindCurrentWorkflowVersionByWorkflowParams struct {
	WorkflowID uuid.UUID `json:"workflow_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindCurrentWorkflowVersionByWorkflow(ctx context.Context, arg FindCurrentWorkflowVersionByWorkflowParams) (WorkflowVersion, error) {
	row := q.db.QueryRowContext(ctx, findCurrentWorkflowVersionByWorkflow, arg.WorkflowID, arg.TenantID)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TenantID,
		&i.ProjectID,
		&i.VersionNo,
		&i.Definition,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProjectByID = `-- name: FindProjectByID :one
SELECT id, tenant_id, name, slug, status, created_at, updated_at
FROM projects
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type FindProjectByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindProjectByID(ctx context.Context, arg FindProjectByIDParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, findProjectByID, arg.ID, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProjectBySlug = `-- name: FindProjectBySlug :one
SELECT id, tenant_id, name, slug, status, created_at, updated_at
FROM projects
WHERE slug = $1 AND tenant_id = $2
LIMIT 1
`

type FindProjectBySlugParams struct {
	Slug     string    `json:"slug"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) FindProjectBySlug(ctx context.Context, arg FindProjectBySlugParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, findProjectBySlug, arg.Slug, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWorkflowByID = `-- name: FindWorkflowByID :one
SELECT id, tenant_id, project_id, slug, name, description, status, current_version, version, created_at, updated_at, draft_definition
FROM workflows
WHERE id = $1 AND tenant_id = $2 AND project_id = $3
LIMIT 1
`

type FindWorkflowByIDParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) FindWorkflowByID(ctx context.Context, arg FindWorkflowByIDParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, findWorkflowByID, arg.ID, arg.TenantID, arg.ProjectID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftDefinition,
	)
	return i, err
}

const findWorkflowBySlug = `-- name: FindWorkflowBySlug :one
SELECT id, tenant_id, project_id, slug, name, description, status, current_version, version, created_at, updated_at, draft_definition
FROM workflows
WHERE slug = $1 AND tenant_id = $2 AND project_id = $3
LIMIT 1
`

type FindWorkflowBySlugParams struct {
	Slug      string    `json:"slug"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) FindWorkflowBySlug(ctx context.Context, arg FindWorkflowBySlugParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, findWorkflowBySlug, arg.Slug, arg.TenantID, arg.ProjectID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftDefinition,
	)
	return i, err
}

const findWorkflowVersionByID = `-- name: FindWorkflowVersionByID :one
SELECT wv.id, wv.workflow_id, wv.tenant_id, wv.project_id, wv.version_no, wv.definition, wv.status, wv.is_current, wv.created_at, wv.updated_at,
       w.slug AS workflow_slug
FROM workflow_versions wv
JOIN workflows w ON w.id = wv.workflow_id
WHERE wv.id = $1 AND wv.tenant_id = $2
LIMIT 1
`

type FindWorkflowVersionByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type FindWorkflowVersionByIDRow struct {
	ID           uuid.UUID       `json:"id"`
	WorkflowID   uuid.UUID       `json:"workflow_id"`
	TenantID     uuid.UUID       `json:"tenant_id"`
	ProjectID    uuid.UUID       `json:"project_id"`
	VersionNo    int32           `json:"version_no"`
	Definition   json.RawMessage `json:"definition"`
	Status       string          `json:"status"`
	IsCurrent    bool            `json:"is_current"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	WorkflowSlug string          `json:"workflow_slug"`
}

func (q *Queries) FindWorkflowVersionByID(ctx context.Context, arg FindWorkflowVersionByIDParams) (FindWorkflowVersionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findWorkflowVersionByID, arg.ID, arg.TenantID)
	var i FindWorkflowVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TenantID,
		&i.ProjectID,
		&i.VersionNo,
		&i.Definition,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkflowSlug,
	)
	return i, err
}

const findWorkflowVersionByNumber = `-- name: FindWorkflowVersionByNumber :one
SELECT id, workflow_id, tenant_id, project_id, version_no, definition, status, is_current, created_at, updated_at
FROM workflow_versions
WHERE workflow_id = $1 AND version_no = $2 AND tenant_id = $3 AND project_id = $4
LIMIT 1
`

type FindWorkflowVersionByNumberParams struct {
	WorkflowID uuid.UUID `json:"workflow_id"`
	VersionNo  int32     `json:"version_no"`
	TenantID   uuid.UUID `json:"tenant_id"`
	ProjectID  uuid.UUID `json:"project_id"`
}

func (q *Queries) FindWorkflowVersionByNumber(ctx context.Context, arg FindWorkflowVersionByNumberParams) (WorkflowVersion, error) {
	row := q.db.QueryRowContext(ctx, findWorkflowVersionByNumber,
		arg.WorkflowID,
		arg.VersionNo,
		arg.TenantID,
		arg.ProjectID,
	)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TenantID,
		&i.ProjectID,
		&i.VersionNo,
		&i.Definition,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuardsByTransition = `-- name: ListGuardsByTransition :many
SELECT g.id, g.transition_id, g.workflow_version_id, g.logic, g.conditions, g.created_at, g.updated_at
FROM transition_guards g
JOIN transitions t ON t.id = g.transition_id
JOIN workflow_versions wv ON wv.id = t.workflow_version_id
WHERE g.transition_id = $1 AND wv.tenant_id = $2 AND wv.project_id = $3
ORDER BY g.created_at ASC
`

type ListGuardsByTransitionParams struct {
	TransitionID uuid.UUID `json:"transition_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
}

func (q *Queries) ListGuardsByTransition(ctx context.Context, arg ListGuardsByTransitionParams) ([]TransitionGuard, error) {
	rows, err := q.db.QueryContext(ctx, listGuardsByTransition, arg.TransitionID, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransitionGuard
	for rows.Next() {
		var i TransitionGuard
		if err := rows.Scan(
			&i.ID,
			&i.TransitionID,
			&i.WorkflowVersionID,
			&i.Logic,
			&i.Conditions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByTenant = `-- name: ListProjectsByTenant :many
SELECT id, tenant_id, name, slug, status, created_at, updated_at
FROM projects
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatesByVersion = `-- name: ListStatesByVersion :many
SELECT s.id, s.workflow_version_id, s.key, s.kind, s.name, s.description, s.instructions,
       s.required_context, s.capabilities, s.policy, s.is_terminal, s.position, s.created_at, s.updated_at
FROM states s
JOIN workflow_versions wv ON wv.id = s.workflow_version_id
WHERE s.workflow_version_id = $1 AND wv.tenant_id = $2 AND wv.project_id = $3
ORDER BY s.created_at ASC
`

type ListStatesByVersionParams struct {
	WorkflowVersionID uuid.UUID `json:"workflow_version_id"`
	TenantID          uuid.UUID `json:"tenant_id"`
	ProjectID         uuid.UUID `json:"project_id"`
}

func (q *Queries) ListStatesByVersion(ctx context.Context, arg ListStatesByVersionParams) ([]State, error) {
	rows, err := q.db.QueryContext(ctx, listStatesByVersion, arg.WorkflowVersionID, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []State
	for rows.Next() {
		var i State
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.Key,
			&i.Kind,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.RequiredContext,
			&i.Capabilities,
			&i.Policy,
			&i.IsTerminal,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitionsByVersion = `-- name: ListTransitionsByVersion :many
SELECT t.id, t.workflow_version_id, t.key, t.source_state_id, t.target_state_id, t.event, t.priority, t.is_active, t.created_at, t.updated_at
FROM transitions t
JOIN workflow_versions wv ON wv.id = t.workflow_version_id
WHERE t.workflow_version_id = $1 AND wv.tenant_id = $2 AND wv.project_id = $3
ORDER BY t.priority ASC
`

type ListTransitionsByVersionParams struct {
	WorkflowVersionID uuid.UUID `json:"workflow_version_id"`
	TenantID          uuid.UUID `json:"tenant_id"`
	ProjectID         uuid.UUID `json:"project_id"`
}

func (q *Queries) ListTransitionsByVersion(ctx context.Context, arg ListTransitionsByVersionParams) ([]Transition, error) {
	rows, err := q.db.QueryContext(ctx, listTransitionsByVersion, arg.WorkflowVersionID, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transition
	for rows.Next() {
		var i Transition
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.Key,
			&i.SourceStateID,
			&i.TargetStateID,
			&i.Event,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVersions = `-- name: ListWorkflowVersions :many
SELECT id, workflow_id, tenant_id, project_id, version_no, definition, status, is_current, created_at, updated_at
FROM workflow_versions
WHERE workflow_id = $1 AND tenant_id = $2 AND project_id = $3
ORDER BY version_no DESC
`

type ListWorkflowVersionsParams struct {
	WorkflowID uuid.UUID `json:"workflow_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	ProjectID  uuid.UUID `json:"project_id"`
}

func (q *Queries) ListWorkflowVersions(ctx context.Context, arg ListWorkflowVersionsParams) ([]WorkflowVersion, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowVersions, arg.WorkflowID, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersion
	for rows.Next() {
		var i WorkflowVersion
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.TenantID,
			&i.ProjectID,
			&i.VersionNo,
			&i.Definition,
			&i.Status,
			&i.IsCurrent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByTenant = `-- name: ListWorkflowsByTenant :many
SELECT id, tenant_id, project_id, slug, name, description, status, current_version, version, created_at, updated_at, draft_definition
FROM workflows
WHERE tenant_id = $1 AND project_id = $2
ORDER BY created_at DESC
`

type ListWorkflowsByTenantParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) ListWorkflowsByTenant(ctx context.Context, arg ListWorkflowsByTenantParams) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowsByTenant, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CurrentVersion,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DraftDefinition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentWorkflowVersion = `-- name: SetCurrentWorkflowVersion :exec
UPDATE workflow_versions
SET is_current = (version_no = $2), updated_at = NOW()
WHERE workflow_id = $1 AND tenant_id = $3 AND project_id = $4
`

type SetCurrentWorkflowVersionParams struct {
	WorkflowID uuid.UUID `json:"workflow_id"`
	VersionNo  int32     `json:"version_no"`
	TenantID   uuid.UUID `json:"tenant_id"`
	ProjectID  uuid.UUID `json:"project_id"`
}

func (q *Queries) SetCurrentWorkflowVersion(ctx context.Context, arg SetCurrentWorkflowVersionParams) error {
	_, err := q.db.ExecContext(ctx, setCurrentWorkflowVersion,
		arg.WorkflowID,
		arg.VersionNo,
		arg.TenantID,
		arg.ProjectID,
	)
	return err
}

const updateWorkflowDraft = `-- name: UpdateWorkflowDraft :one
UPDATE workflows
SET name = $4,
    description = $5,
    draft_definition = $6,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3 AND version = $7
RETURNING id, tenant_id, project_id, slug, name, description, status, current_version, version, created_at, updated_at, draft_definition
`

type UpdateWorkflowDraftParams struct {
	ID              uuid.UUID       `json:"id"`
	TenantID        uuid.UUID       `json:"tenant_id"`
	ProjectID       uuid.UUID       `json:"project_id"`
	Name            string          `json:"name"`
	Description     sql.NullString  `json:"description"`
	DraftDefinition json.RawMessage `json:"draft_definition"`
	Version         int32           `json:"version"`
}

func (q *Queries) UpdateWorkflowDraft(ctx context.Context, arg UpdateWorkflowDraftParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowDraft,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.DraftDefinition,
		arg.Version,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftDefinition,
	)
	return i, err
}

const updateWorkflowStatus = `-- name: UpdateWorkflowStatus :one
UPDATE workflows
SET status = $4, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3 AND version = $5
RETURNING id, tenant_id, project_id, slug, name, description, status, current_version, version, created_at, updated_at, draft_definition
`

type UpdateWorkflowStatusParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
	Version   int32     `json:"version"`
}

func (q *Queries) UpdateWorkflowStatus(ctx context.Context, arg UpdateWorkflowStatusParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowStatus,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.Status,
		arg.Version,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftDefinition,
	)
	return i, err
}

const updateWorkflowVersion = `-- name: UpdateWorkflowVersion :one
UPDATE workflows
SET version = version + 1, current_version = $4, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND project_id = $3 AND version = $5
RETURNING id, tenant_id, project_id, slug, name, description, status, current_version, version, created_at, updated_at, draft_definition
`

type UpdateWorkflowVersionParams struct {
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	CurrentVersion int32     `json:"current_version"`
	Version        int32     `json:"version"`
}

func (q *Queries) UpdateWorkflowVersion(ctx context.Context, arg UpdateWorkflowVersionParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowVersion,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.CurrentVersion,
		arg.Version,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftDefinition,
	)
	return i, err
}
